package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Dicombulkdata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.studyUID
     *
     * @mbg.generated
     */
    private String studyuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.seriesUID
     *
     * @mbg.generated
     */
    private String seriesuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.instanceUID
     *
     * @mbg.generated
     */
    private String instanceuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.binaryValuePath
     *
     * @mbg.generated
     */
    private String binaryvaluepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomBulkData.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.id
     *
     * @return the value of public.DicomBulkData.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.id
     *
     * @param id the value for public.DicomBulkData.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.studyUID
     *
     * @return the value of public.DicomBulkData.studyUID
     *
     * @mbg.generated
     */
    public String getStudyuid() {
        return studyuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.studyUID
     *
     * @param studyuid the value for public.DicomBulkData.studyUID
     *
     * @mbg.generated
     */
    public void setStudyuid(String studyuid) {
        this.studyuid = studyuid == null ? null : studyuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.seriesUID
     *
     * @return the value of public.DicomBulkData.seriesUID
     *
     * @mbg.generated
     */
    public String getSeriesuid() {
        return seriesuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.seriesUID
     *
     * @param seriesuid the value for public.DicomBulkData.seriesUID
     *
     * @mbg.generated
     */
    public void setSeriesuid(String seriesuid) {
        this.seriesuid = seriesuid == null ? null : seriesuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.instanceUID
     *
     * @return the value of public.DicomBulkData.instanceUID
     *
     * @mbg.generated
     */
    public String getInstanceuid() {
        return instanceuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.instanceUID
     *
     * @param instanceuid the value for public.DicomBulkData.instanceUID
     *
     * @mbg.generated
     */
    public void setInstanceuid(String instanceuid) {
        this.instanceuid = instanceuid == null ? null : instanceuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.filename
     *
     * @return the value of public.DicomBulkData.filename
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.filename
     *
     * @param filename the value for public.DicomBulkData.filename
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.binaryValuePath
     *
     * @return the value of public.DicomBulkData.binaryValuePath
     *
     * @mbg.generated
     */
    public String getBinaryvaluepath() {
        return binaryvaluepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.binaryValuePath
     *
     * @param binaryvaluepath the value for public.DicomBulkData.binaryValuePath
     *
     * @mbg.generated
     */
    public void setBinaryvaluepath(String binaryvaluepath) {
        this.binaryvaluepath = binaryvaluepath == null ? null : binaryvaluepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.createdAt
     *
     * @return the value of public.DicomBulkData.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.createdAt
     *
     * @param createdat the value for public.DicomBulkData.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomBulkData.updatedAt
     *
     * @return the value of public.DicomBulkData.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomBulkData.updatedAt
     *
     * @param updatedat the value for public.DicomBulkData.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}