package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DicomcodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public DicomcodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andX00080100IsNull() {
            addCriterion("x00080100 is null");
            return (Criteria) this;
        }

        public Criteria andX00080100IsNotNull() {
            addCriterion("x00080100 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080100EqualTo(String value) {
            addCriterion("x00080100 =", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100NotEqualTo(String value) {
            addCriterion("x00080100 <>", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100GreaterThan(String value) {
            addCriterion("x00080100 >", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100GreaterThanOrEqualTo(String value) {
            addCriterion("x00080100 >=", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100LessThan(String value) {
            addCriterion("x00080100 <", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100LessThanOrEqualTo(String value) {
            addCriterion("x00080100 <=", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100Like(String value) {
            addCriterion("x00080100 like", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100NotLike(String value) {
            addCriterion("x00080100 not like", value, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100In(List<String> values) {
            addCriterion("x00080100 in", values, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100NotIn(List<String> values) {
            addCriterion("x00080100 not in", values, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100Between(String value1, String value2) {
            addCriterion("x00080100 between", value1, value2, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080100NotBetween(String value1, String value2) {
            addCriterion("x00080100 not between", value1, value2, "x00080100");
            return (Criteria) this;
        }

        public Criteria andX00080102IsNull() {
            addCriterion("x00080102 is null");
            return (Criteria) this;
        }

        public Criteria andX00080102IsNotNull() {
            addCriterion("x00080102 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080102EqualTo(String value) {
            addCriterion("x00080102 =", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102NotEqualTo(String value) {
            addCriterion("x00080102 <>", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102GreaterThan(String value) {
            addCriterion("x00080102 >", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102GreaterThanOrEqualTo(String value) {
            addCriterion("x00080102 >=", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102LessThan(String value) {
            addCriterion("x00080102 <", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102LessThanOrEqualTo(String value) {
            addCriterion("x00080102 <=", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102Like(String value) {
            addCriterion("x00080102 like", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102NotLike(String value) {
            addCriterion("x00080102 not like", value, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102In(List<String> values) {
            addCriterion("x00080102 in", values, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102NotIn(List<String> values) {
            addCriterion("x00080102 not in", values, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102Between(String value1, String value2) {
            addCriterion("x00080102 between", value1, value2, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080102NotBetween(String value1, String value2) {
            addCriterion("x00080102 not between", value1, value2, "x00080102");
            return (Criteria) this;
        }

        public Criteria andX00080103IsNull() {
            addCriterion("x00080103 is null");
            return (Criteria) this;
        }

        public Criteria andX00080103IsNotNull() {
            addCriterion("x00080103 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080103EqualTo(String value) {
            addCriterion("x00080103 =", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103NotEqualTo(String value) {
            addCriterion("x00080103 <>", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103GreaterThan(String value) {
            addCriterion("x00080103 >", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103GreaterThanOrEqualTo(String value) {
            addCriterion("x00080103 >=", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103LessThan(String value) {
            addCriterion("x00080103 <", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103LessThanOrEqualTo(String value) {
            addCriterion("x00080103 <=", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103Like(String value) {
            addCriterion("x00080103 like", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103NotLike(String value) {
            addCriterion("x00080103 not like", value, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103In(List<String> values) {
            addCriterion("x00080103 in", values, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103NotIn(List<String> values) {
            addCriterion("x00080103 not in", values, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103Between(String value1, String value2) {
            addCriterion("x00080103 between", value1, value2, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080103NotBetween(String value1, String value2) {
            addCriterion("x00080103 not between", value1, value2, "x00080103");
            return (Criteria) this;
        }

        public Criteria andX00080104IsNull() {
            addCriterion("x00080104 is null");
            return (Criteria) this;
        }

        public Criteria andX00080104IsNotNull() {
            addCriterion("x00080104 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080104EqualTo(String value) {
            addCriterion("x00080104 =", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104NotEqualTo(String value) {
            addCriterion("x00080104 <>", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104GreaterThan(String value) {
            addCriterion("x00080104 >", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104GreaterThanOrEqualTo(String value) {
            addCriterion("x00080104 >=", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104LessThan(String value) {
            addCriterion("x00080104 <", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104LessThanOrEqualTo(String value) {
            addCriterion("x00080104 <=", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104Like(String value) {
            addCriterion("x00080104 like", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104NotLike(String value) {
            addCriterion("x00080104 not like", value, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104In(List<String> values) {
            addCriterion("x00080104 in", values, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104NotIn(List<String> values) {
            addCriterion("x00080104 not in", values, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104Between(String value1, String value2) {
            addCriterion("x00080104 between", value1, value2, "x00080104");
            return (Criteria) this;
        }

        public Criteria andX00080104NotBetween(String value1, String value2) {
            addCriterion("x00080104 not between", value1, value2, "x00080104");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNull() {
            addCriterion("createdAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNotNull() {
            addCriterion("createdAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedatEqualTo(Date value) {
            addCriterion("createdAt =", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotEqualTo(Date value) {
            addCriterion("createdAt <>", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThan(Date value) {
            addCriterion("createdAt >", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("createdAt >=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThan(Date value) {
            addCriterion("createdAt <", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThanOrEqualTo(Date value) {
            addCriterion("createdAt <=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatIn(List<Date> values) {
            addCriterion("createdAt in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotIn(List<Date> values) {
            addCriterion("createdAt not in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatBetween(Date value1, Date value2) {
            addCriterion("createdAt between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotBetween(Date value1, Date value2) {
            addCriterion("createdAt not between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNull() {
            addCriterion("updatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNotNull() {
            addCriterion("updatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatEqualTo(Date value) {
            addCriterion("updatedAt =", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotEqualTo(Date value) {
            addCriterion("updatedAt <>", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThan(Date value) {
            addCriterion("updatedAt >", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedAt >=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThan(Date value) {
            addCriterion("updatedAt <", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThanOrEqualTo(Date value) {
            addCriterion("updatedAt <=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIn(List<Date> values) {
            addCriterion("updatedAt in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotIn(List<Date> values) {
            addCriterion("updatedAt not in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatBetween(Date value1, Date value2) {
            addCriterion("updatedAt between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotBetween(Date value1, Date value2) {
            addCriterion("updatedAt not between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidIsNull() {
            addCriterion("SOPInstanceUID is null");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidIsNotNull() {
            addCriterion("SOPInstanceUID is not null");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidEqualTo(String value) {
            addCriterion("SOPInstanceUID =", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidNotEqualTo(String value) {
            addCriterion("SOPInstanceUID <>", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidGreaterThan(String value) {
            addCriterion("SOPInstanceUID >", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidGreaterThanOrEqualTo(String value) {
            addCriterion("SOPInstanceUID >=", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidLessThan(String value) {
            addCriterion("SOPInstanceUID <", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidLessThanOrEqualTo(String value) {
            addCriterion("SOPInstanceUID <=", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidLike(String value) {
            addCriterion("SOPInstanceUID like", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidNotLike(String value) {
            addCriterion("SOPInstanceUID not like", value, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidIn(List<String> values) {
            addCriterion("SOPInstanceUID in", values, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidNotIn(List<String> values) {
            addCriterion("SOPInstanceUID not in", values, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidBetween(String value1, String value2) {
            addCriterion("SOPInstanceUID between", value1, value2, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andSopinstanceuidNotBetween(String value1, String value2) {
            addCriterion("SOPInstanceUID not between", value1, value2, "sopinstanceuid");
            return (Criteria) this;
        }

        public Criteria andX0040a088IsNull() {
            addCriterion("x0040A088 is null");
            return (Criteria) this;
        }

        public Criteria andX0040a088IsNotNull() {
            addCriterion("x0040A088 is not null");
            return (Criteria) this;
        }

        public Criteria andX0040a088EqualTo(Integer value) {
            addCriterion("x0040A088 =", value, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088NotEqualTo(Integer value) {
            addCriterion("x0040A088 <>", value, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088GreaterThan(Integer value) {
            addCriterion("x0040A088 >", value, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088GreaterThanOrEqualTo(Integer value) {
            addCriterion("x0040A088 >=", value, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088LessThan(Integer value) {
            addCriterion("x0040A088 <", value, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088LessThanOrEqualTo(Integer value) {
            addCriterion("x0040A088 <=", value, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088In(List<Integer> values) {
            addCriterion("x0040A088 in", values, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088NotIn(List<Integer> values) {
            addCriterion("x0040A088 not in", values, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088Between(Integer value1, Integer value2) {
            addCriterion("x0040A088 between", value1, value2, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andX0040a088NotBetween(Integer value1, Integer value2) {
            addCriterion("x0040A088 not between", value1, value2, "x0040a088");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidIsNull() {
            addCriterion("ConceptNameCodeId is null");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidIsNotNull() {
            addCriterion("ConceptNameCodeId is not null");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidEqualTo(Integer value) {
            addCriterion("ConceptNameCodeId =", value, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidNotEqualTo(Integer value) {
            addCriterion("ConceptNameCodeId <>", value, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidGreaterThan(Integer value) {
            addCriterion("ConceptNameCodeId >", value, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ConceptNameCodeId >=", value, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidLessThan(Integer value) {
            addCriterion("ConceptNameCodeId <", value, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidLessThanOrEqualTo(Integer value) {
            addCriterion("ConceptNameCodeId <=", value, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidIn(List<Integer> values) {
            addCriterion("ConceptNameCodeId in", values, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidNotIn(List<Integer> values) {
            addCriterion("ConceptNameCodeId not in", values, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidBetween(Integer value1, Integer value2) {
            addCriterion("ConceptNameCodeId between", value1, value2, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptnamecodeidNotBetween(Integer value1, Integer value2) {
            addCriterion("ConceptNameCodeId not between", value1, value2, "conceptnamecodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidIsNull() {
            addCriterion("ConceptCodeId is null");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidIsNotNull() {
            addCriterion("ConceptCodeId is not null");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidEqualTo(Integer value) {
            addCriterion("ConceptCodeId =", value, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidNotEqualTo(Integer value) {
            addCriterion("ConceptCodeId <>", value, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidGreaterThan(Integer value) {
            addCriterion("ConceptCodeId >", value, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ConceptCodeId >=", value, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidLessThan(Integer value) {
            addCriterion("ConceptCodeId <", value, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidLessThanOrEqualTo(Integer value) {
            addCriterion("ConceptCodeId <=", value, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidIn(List<Integer> values) {
            addCriterion("ConceptCodeId in", values, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidNotIn(List<Integer> values) {
            addCriterion("ConceptCodeId not in", values, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidBetween(Integer value1, Integer value2) {
            addCriterion("ConceptCodeId between", value1, value2, "conceptcodeid");
            return (Criteria) this;
        }

        public Criteria andConceptcodeidNotBetween(Integer value1, Integer value2) {
            addCriterion("ConceptCodeId not between", value1, value2, "conceptcodeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.DicomCode
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.DicomCode
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}