package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Dicomcode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.x00080100
     *
     * @mbg.generated
     */
    private String x00080100;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.x00080102
     *
     * @mbg.generated
     */
    private String x00080102;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.x00080103
     *
     * @mbg.generated
     */
    private String x00080103;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.x00080104
     *
     * @mbg.generated
     */
    private String x00080104;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.SOPInstanceUID
     *
     * @mbg.generated
     */
    private String sopinstanceuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.x0040A088
     *
     * @mbg.generated
     */
    private Integer x0040a088;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.ConceptNameCodeId
     *
     * @mbg.generated
     */
    private Integer conceptnamecodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomCode.ConceptCodeId
     *
     * @mbg.generated
     */
    private Integer conceptcodeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.id
     *
     * @return the value of public.DicomCode.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.id
     *
     * @param id the value for public.DicomCode.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.x00080100
     *
     * @return the value of public.DicomCode.x00080100
     *
     * @mbg.generated
     */
    public String getX00080100() {
        return x00080100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.x00080100
     *
     * @param x00080100 the value for public.DicomCode.x00080100
     *
     * @mbg.generated
     */
    public void setX00080100(String x00080100) {
        this.x00080100 = x00080100 == null ? null : x00080100.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.x00080102
     *
     * @return the value of public.DicomCode.x00080102
     *
     * @mbg.generated
     */
    public String getX00080102() {
        return x00080102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.x00080102
     *
     * @param x00080102 the value for public.DicomCode.x00080102
     *
     * @mbg.generated
     */
    public void setX00080102(String x00080102) {
        this.x00080102 = x00080102 == null ? null : x00080102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.x00080103
     *
     * @return the value of public.DicomCode.x00080103
     *
     * @mbg.generated
     */
    public String getX00080103() {
        return x00080103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.x00080103
     *
     * @param x00080103 the value for public.DicomCode.x00080103
     *
     * @mbg.generated
     */
    public void setX00080103(String x00080103) {
        this.x00080103 = x00080103 == null ? null : x00080103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.x00080104
     *
     * @return the value of public.DicomCode.x00080104
     *
     * @mbg.generated
     */
    public String getX00080104() {
        return x00080104;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.x00080104
     *
     * @param x00080104 the value for public.DicomCode.x00080104
     *
     * @mbg.generated
     */
    public void setX00080104(String x00080104) {
        this.x00080104 = x00080104 == null ? null : x00080104.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.createdAt
     *
     * @return the value of public.DicomCode.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.createdAt
     *
     * @param createdat the value for public.DicomCode.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.updatedAt
     *
     * @return the value of public.DicomCode.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.updatedAt
     *
     * @param updatedat the value for public.DicomCode.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.SOPInstanceUID
     *
     * @return the value of public.DicomCode.SOPInstanceUID
     *
     * @mbg.generated
     */
    public String getSopinstanceuid() {
        return sopinstanceuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.SOPInstanceUID
     *
     * @param sopinstanceuid the value for public.DicomCode.SOPInstanceUID
     *
     * @mbg.generated
     */
    public void setSopinstanceuid(String sopinstanceuid) {
        this.sopinstanceuid = sopinstanceuid == null ? null : sopinstanceuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.x0040A088
     *
     * @return the value of public.DicomCode.x0040A088
     *
     * @mbg.generated
     */
    public Integer getX0040a088() {
        return x0040a088;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.x0040A088
     *
     * @param x0040a088 the value for public.DicomCode.x0040A088
     *
     * @mbg.generated
     */
    public void setX0040a088(Integer x0040a088) {
        this.x0040a088 = x0040a088;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.ConceptNameCodeId
     *
     * @return the value of public.DicomCode.ConceptNameCodeId
     *
     * @mbg.generated
     */
    public Integer getConceptnamecodeid() {
        return conceptnamecodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.ConceptNameCodeId
     *
     * @param conceptnamecodeid the value for public.DicomCode.ConceptNameCodeId
     *
     * @mbg.generated
     */
    public void setConceptnamecodeid(Integer conceptnamecodeid) {
        this.conceptnamecodeid = conceptnamecodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomCode.ConceptCodeId
     *
     * @return the value of public.DicomCode.ConceptCodeId
     *
     * @mbg.generated
     */
    public Integer getConceptcodeid() {
        return conceptcodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomCode.ConceptCodeId
     *
     * @param conceptcodeid the value for public.DicomCode.ConceptCodeId
     *
     * @mbg.generated
     */
    public void setConceptcodeid(Integer conceptcodeid) {
        this.conceptcodeid = conceptcodeid;
    }
}