package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Dicomtojpegtask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.studyUID
     *
     * @mbg.generated
     */
    private String studyuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.seriesUID
     *
     * @mbg.generated
     */
    private String seriesuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.instanceUID
     *
     * @mbg.generated
     */
    private String instanceuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.taskTime
     *
     * @mbg.generated
     */
    private Date tasktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.finishedTime
     *
     * @mbg.generated
     */
    private Date finishedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.fileSize
     *
     * @mbg.generated
     */
    private String filesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomToJpegTask.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.id
     *
     * @return the value of public.DicomToJpegTask.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.id
     *
     * @param id the value for public.DicomToJpegTask.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.studyUID
     *
     * @return the value of public.DicomToJpegTask.studyUID
     *
     * @mbg.generated
     */
    public String getStudyuid() {
        return studyuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.studyUID
     *
     * @param studyuid the value for public.DicomToJpegTask.studyUID
     *
     * @mbg.generated
     */
    public void setStudyuid(String studyuid) {
        this.studyuid = studyuid == null ? null : studyuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.seriesUID
     *
     * @return the value of public.DicomToJpegTask.seriesUID
     *
     * @mbg.generated
     */
    public String getSeriesuid() {
        return seriesuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.seriesUID
     *
     * @param seriesuid the value for public.DicomToJpegTask.seriesUID
     *
     * @mbg.generated
     */
    public void setSeriesuid(String seriesuid) {
        this.seriesuid = seriesuid == null ? null : seriesuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.instanceUID
     *
     * @return the value of public.DicomToJpegTask.instanceUID
     *
     * @mbg.generated
     */
    public String getInstanceuid() {
        return instanceuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.instanceUID
     *
     * @param instanceuid the value for public.DicomToJpegTask.instanceUID
     *
     * @mbg.generated
     */
    public void setInstanceuid(String instanceuid) {
        this.instanceuid = instanceuid == null ? null : instanceuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.message
     *
     * @return the value of public.DicomToJpegTask.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.message
     *
     * @param message the value for public.DicomToJpegTask.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.status
     *
     * @return the value of public.DicomToJpegTask.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.status
     *
     * @param status the value for public.DicomToJpegTask.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.taskTime
     *
     * @return the value of public.DicomToJpegTask.taskTime
     *
     * @mbg.generated
     */
    public Date getTasktime() {
        return tasktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.taskTime
     *
     * @param tasktime the value for public.DicomToJpegTask.taskTime
     *
     * @mbg.generated
     */
    public void setTasktime(Date tasktime) {
        this.tasktime = tasktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.finishedTime
     *
     * @return the value of public.DicomToJpegTask.finishedTime
     *
     * @mbg.generated
     */
    public Date getFinishedtime() {
        return finishedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.finishedTime
     *
     * @param finishedtime the value for public.DicomToJpegTask.finishedTime
     *
     * @mbg.generated
     */
    public void setFinishedtime(Date finishedtime) {
        this.finishedtime = finishedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.fileSize
     *
     * @return the value of public.DicomToJpegTask.fileSize
     *
     * @mbg.generated
     */
    public String getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.fileSize
     *
     * @param filesize the value for public.DicomToJpegTask.fileSize
     *
     * @mbg.generated
     */
    public void setFilesize(String filesize) {
        this.filesize = filesize == null ? null : filesize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.createdAt
     *
     * @return the value of public.DicomToJpegTask.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.createdAt
     *
     * @param createdat the value for public.DicomToJpegTask.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomToJpegTask.updatedAt
     *
     * @return the value of public.DicomToJpegTask.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomToJpegTask.updatedAt
     *
     * @param updatedat the value for public.DicomToJpegTask.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}