package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Dicomcontentsq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.x0040A010
     *
     * @mbg.generated
     */
    private String x0040a010;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.x0040A040
     *
     * @mbg.generated
     */
    private String x0040a040;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.x0040A160
     *
     * @mbg.generated
     */
    private String x0040a160;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.DicomContentSQ.SOPInstanceUID
     *
     * @mbg.generated
     */
    private String sopinstanceuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.id
     *
     * @return the value of public.DicomContentSQ.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.id
     *
     * @param id the value for public.DicomContentSQ.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.x0040A010
     *
     * @return the value of public.DicomContentSQ.x0040A010
     *
     * @mbg.generated
     */
    public String getX0040a010() {
        return x0040a010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.x0040A010
     *
     * @param x0040a010 the value for public.DicomContentSQ.x0040A010
     *
     * @mbg.generated
     */
    public void setX0040a010(String x0040a010) {
        this.x0040a010 = x0040a010 == null ? null : x0040a010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.x0040A040
     *
     * @return the value of public.DicomContentSQ.x0040A040
     *
     * @mbg.generated
     */
    public String getX0040a040() {
        return x0040a040;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.x0040A040
     *
     * @param x0040a040 the value for public.DicomContentSQ.x0040A040
     *
     * @mbg.generated
     */
    public void setX0040a040(String x0040a040) {
        this.x0040a040 = x0040a040 == null ? null : x0040a040.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.x0040A160
     *
     * @return the value of public.DicomContentSQ.x0040A160
     *
     * @mbg.generated
     */
    public String getX0040a160() {
        return x0040a160;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.x0040A160
     *
     * @param x0040a160 the value for public.DicomContentSQ.x0040A160
     *
     * @mbg.generated
     */
    public void setX0040a160(String x0040a160) {
        this.x0040a160 = x0040a160 == null ? null : x0040a160.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.createdAt
     *
     * @return the value of public.DicomContentSQ.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.createdAt
     *
     * @param createdat the value for public.DicomContentSQ.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.updatedAt
     *
     * @return the value of public.DicomContentSQ.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.updatedAt
     *
     * @param updatedat the value for public.DicomContentSQ.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.DicomContentSQ.SOPInstanceUID
     *
     * @return the value of public.DicomContentSQ.SOPInstanceUID
     *
     * @mbg.generated
     */
    public String getSopinstanceuid() {
        return sopinstanceuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.DicomContentSQ.SOPInstanceUID
     *
     * @param sopinstanceuid the value for public.DicomContentSQ.SOPInstanceUID
     *
     * @mbg.generated
     */
    public void setSopinstanceuid(String sopinstanceuid) {
        this.sopinstanceuid = sopinstanceuid == null ? null : sopinstanceuid.trim();
    }
}