package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class InstanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public InstanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andX00080018IsNull() {
            addCriterion("x00080018 is null");
            return (Criteria) this;
        }

        public Criteria andX00080018IsNotNull() {
            addCriterion("x00080018 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080018EqualTo(String value) {
            addCriterion("x00080018 =", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018NotEqualTo(String value) {
            addCriterion("x00080018 <>", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018GreaterThan(String value) {
            addCriterion("x00080018 >", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018GreaterThanOrEqualTo(String value) {
            addCriterion("x00080018 >=", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018LessThan(String value) {
            addCriterion("x00080018 <", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018LessThanOrEqualTo(String value) {
            addCriterion("x00080018 <=", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018Like(String value) {
            addCriterion("x00080018 like", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018NotLike(String value) {
            addCriterion("x00080018 not like", value, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018In(List<String> values) {
            addCriterion("x00080018 in", values, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018NotIn(List<String> values) {
            addCriterion("x00080018 not in", values, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018Between(String value1, String value2) {
            addCriterion("x00080018 between", value1, value2, "x00080018");
            return (Criteria) this;
        }

        public Criteria andX00080018NotBetween(String value1, String value2) {
            addCriterion("x00080018 not between", value1, value2, "x00080018");
            return (Criteria) this;
        }

        public Criteria andInstancepathIsNull() {
            addCriterion("instancePath is null");
            return (Criteria) this;
        }

        public Criteria andInstancepathIsNotNull() {
            addCriterion("instancePath is not null");
            return (Criteria) this;
        }

        public Criteria andInstancepathEqualTo(String value) {
            addCriterion("instancePath =", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathNotEqualTo(String value) {
            addCriterion("instancePath <>", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathGreaterThan(String value) {
            addCriterion("instancePath >", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathGreaterThanOrEqualTo(String value) {
            addCriterion("instancePath >=", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathLessThan(String value) {
            addCriterion("instancePath <", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathLessThanOrEqualTo(String value) {
            addCriterion("instancePath <=", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathLike(String value) {
            addCriterion("instancePath like", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathNotLike(String value) {
            addCriterion("instancePath not like", value, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathIn(List<String> values) {
            addCriterion("instancePath in", values, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathNotIn(List<String> values) {
            addCriterion("instancePath not in", values, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathBetween(String value1, String value2) {
            addCriterion("instancePath between", value1, value2, "instancepath");
            return (Criteria) this;
        }

        public Criteria andInstancepathNotBetween(String value1, String value2) {
            addCriterion("instancePath not between", value1, value2, "instancepath");
            return (Criteria) this;
        }

        public Criteria andX00020010IsNull() {
            addCriterion("x00020010 is null");
            return (Criteria) this;
        }

        public Criteria andX00020010IsNotNull() {
            addCriterion("x00020010 is not null");
            return (Criteria) this;
        }

        public Criteria andX00020010EqualTo(String value) {
            addCriterion("x00020010 =", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010NotEqualTo(String value) {
            addCriterion("x00020010 <>", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010GreaterThan(String value) {
            addCriterion("x00020010 >", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010GreaterThanOrEqualTo(String value) {
            addCriterion("x00020010 >=", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010LessThan(String value) {
            addCriterion("x00020010 <", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010LessThanOrEqualTo(String value) {
            addCriterion("x00020010 <=", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010Like(String value) {
            addCriterion("x00020010 like", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010NotLike(String value) {
            addCriterion("x00020010 not like", value, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010In(List<String> values) {
            addCriterion("x00020010 in", values, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010NotIn(List<String> values) {
            addCriterion("x00020010 not in", values, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010Between(String value1, String value2) {
            addCriterion("x00020010 between", value1, value2, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX00020010NotBetween(String value1, String value2) {
            addCriterion("x00020010 not between", value1, value2, "x00020010");
            return (Criteria) this;
        }

        public Criteria andX0020000dIsNull() {
            addCriterion("x0020000D is null");
            return (Criteria) this;
        }

        public Criteria andX0020000dIsNotNull() {
            addCriterion("x0020000D is not null");
            return (Criteria) this;
        }

        public Criteria andX0020000dEqualTo(String value) {
            addCriterion("x0020000D =", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotEqualTo(String value) {
            addCriterion("x0020000D <>", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dGreaterThan(String value) {
            addCriterion("x0020000D >", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dGreaterThanOrEqualTo(String value) {
            addCriterion("x0020000D >=", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLessThan(String value) {
            addCriterion("x0020000D <", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLessThanOrEqualTo(String value) {
            addCriterion("x0020000D <=", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLike(String value) {
            addCriterion("x0020000D like", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotLike(String value) {
            addCriterion("x0020000D not like", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dIn(List<String> values) {
            addCriterion("x0020000D in", values, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotIn(List<String> values) {
            addCriterion("x0020000D not in", values, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dBetween(String value1, String value2) {
            addCriterion("x0020000D between", value1, value2, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotBetween(String value1, String value2) {
            addCriterion("x0020000D not between", value1, value2, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000eIsNull() {
            addCriterion("x0020000E is null");
            return (Criteria) this;
        }

        public Criteria andX0020000eIsNotNull() {
            addCriterion("x0020000E is not null");
            return (Criteria) this;
        }

        public Criteria andX0020000eEqualTo(String value) {
            addCriterion("x0020000E =", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotEqualTo(String value) {
            addCriterion("x0020000E <>", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eGreaterThan(String value) {
            addCriterion("x0020000E >", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eGreaterThanOrEqualTo(String value) {
            addCriterion("x0020000E >=", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eLessThan(String value) {
            addCriterion("x0020000E <", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eLessThanOrEqualTo(String value) {
            addCriterion("x0020000E <=", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eLike(String value) {
            addCriterion("x0020000E like", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotLike(String value) {
            addCriterion("x0020000E not like", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eIn(List<String> values) {
            addCriterion("x0020000E in", values, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotIn(List<String> values) {
            addCriterion("x0020000E not in", values, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eBetween(String value1, String value2) {
            addCriterion("x0020000E between", value1, value2, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotBetween(String value1, String value2) {
            addCriterion("x0020000E not between", value1, value2, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX00080016IsNull() {
            addCriterion("x00080016 is null");
            return (Criteria) this;
        }

        public Criteria andX00080016IsNotNull() {
            addCriterion("x00080016 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080016EqualTo(String value) {
            addCriterion("x00080016 =", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016NotEqualTo(String value) {
            addCriterion("x00080016 <>", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016GreaterThan(String value) {
            addCriterion("x00080016 >", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016GreaterThanOrEqualTo(String value) {
            addCriterion("x00080016 >=", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016LessThan(String value) {
            addCriterion("x00080016 <", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016LessThanOrEqualTo(String value) {
            addCriterion("x00080016 <=", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016Like(String value) {
            addCriterion("x00080016 like", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016NotLike(String value) {
            addCriterion("x00080016 not like", value, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016In(List<String> values) {
            addCriterion("x00080016 in", values, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016NotIn(List<String> values) {
            addCriterion("x00080016 not in", values, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016Between(String value1, String value2) {
            addCriterion("x00080016 between", value1, value2, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080016NotBetween(String value1, String value2) {
            addCriterion("x00080016 not between", value1, value2, "x00080016");
            return (Criteria) this;
        }

        public Criteria andX00080023IsNull() {
            addCriterion("x00080023 is null");
            return (Criteria) this;
        }

        public Criteria andX00080023IsNotNull() {
            addCriterion("x00080023 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080023EqualTo(Date value) {
            addCriterionForJDBCDate("x00080023 =", value, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023NotEqualTo(Date value) {
            addCriterionForJDBCDate("x00080023 <>", value, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023GreaterThan(Date value) {
            addCriterionForJDBCDate("x00080023 >", value, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00080023 >=", value, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023LessThan(Date value) {
            addCriterionForJDBCDate("x00080023 <", value, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00080023 <=", value, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023In(List<Date> values) {
            addCriterionForJDBCDate("x00080023 in", values, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023NotIn(List<Date> values) {
            addCriterionForJDBCDate("x00080023 not in", values, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023Between(Date value1, Date value2) {
            addCriterionForJDBCDate("x00080023 between", value1, value2, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080023NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("x00080023 not between", value1, value2, "x00080023");
            return (Criteria) this;
        }

        public Criteria andX00080033IsNull() {
            addCriterion("x00080033 is null");
            return (Criteria) this;
        }

        public Criteria andX00080033IsNotNull() {
            addCriterion("x00080033 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080033EqualTo(Short value) {
            addCriterion("x00080033 =", value, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033NotEqualTo(Short value) {
            addCriterion("x00080033 <>", value, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033GreaterThan(Short value) {
            addCriterion("x00080033 >", value, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033GreaterThanOrEqualTo(Short value) {
            addCriterion("x00080033 >=", value, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033LessThan(Short value) {
            addCriterion("x00080033 <", value, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033LessThanOrEqualTo(Short value) {
            addCriterion("x00080033 <=", value, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033In(List<Short> values) {
            addCriterion("x00080033 in", values, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033NotIn(List<Short> values) {
            addCriterion("x00080033 not in", values, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033Between(Short value1, Short value2) {
            addCriterion("x00080033 between", value1, value2, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00080033NotBetween(Short value1, Short value2) {
            addCriterion("x00080033 not between", value1, value2, "x00080033");
            return (Criteria) this;
        }

        public Criteria andX00200013IsNull() {
            addCriterion("x00200013 is null");
            return (Criteria) this;
        }

        public Criteria andX00200013IsNotNull() {
            addCriterion("x00200013 is not null");
            return (Criteria) this;
        }

        public Criteria andX00200013EqualTo(String value) {
            addCriterion("x00200013 =", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013NotEqualTo(String value) {
            addCriterion("x00200013 <>", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013GreaterThan(String value) {
            addCriterion("x00200013 >", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013GreaterThanOrEqualTo(String value) {
            addCriterion("x00200013 >=", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013LessThan(String value) {
            addCriterion("x00200013 <", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013LessThanOrEqualTo(String value) {
            addCriterion("x00200013 <=", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013Like(String value) {
            addCriterion("x00200013 like", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013NotLike(String value) {
            addCriterion("x00200013 not like", value, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013In(List<String> values) {
            addCriterion("x00200013 in", values, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013NotIn(List<String> values) {
            addCriterion("x00200013 not in", values, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013Between(String value1, String value2) {
            addCriterion("x00200013 between", value1, value2, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00200013NotBetween(String value1, String value2) {
            addCriterion("x00200013 not between", value1, value2, "x00200013");
            return (Criteria) this;
        }

        public Criteria andX00280008IsNull() {
            addCriterion("x00280008 is null");
            return (Criteria) this;
        }

        public Criteria andX00280008IsNotNull() {
            addCriterion("x00280008 is not null");
            return (Criteria) this;
        }

        public Criteria andX00280008EqualTo(String value) {
            addCriterion("x00280008 =", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008NotEqualTo(String value) {
            addCriterion("x00280008 <>", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008GreaterThan(String value) {
            addCriterion("x00280008 >", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008GreaterThanOrEqualTo(String value) {
            addCriterion("x00280008 >=", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008LessThan(String value) {
            addCriterion("x00280008 <", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008LessThanOrEqualTo(String value) {
            addCriterion("x00280008 <=", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008Like(String value) {
            addCriterion("x00280008 like", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008NotLike(String value) {
            addCriterion("x00280008 not like", value, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008In(List<String> values) {
            addCriterion("x00280008 in", values, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008NotIn(List<String> values) {
            addCriterion("x00280008 not in", values, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008Between(String value1, String value2) {
            addCriterion("x00280008 between", value1, value2, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00280008NotBetween(String value1, String value2) {
            addCriterion("x00280008 not between", value1, value2, "x00280008");
            return (Criteria) this;
        }

        public Criteria andX00281050IsNull() {
            addCriterion("x00281050 is null");
            return (Criteria) this;
        }

        public Criteria andX00281050IsNotNull() {
            addCriterion("x00281050 is not null");
            return (Criteria) this;
        }

        public Criteria andX00281050EqualTo(String value) {
            addCriterion("x00281050 =", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050NotEqualTo(String value) {
            addCriterion("x00281050 <>", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050GreaterThan(String value) {
            addCriterion("x00281050 >", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050GreaterThanOrEqualTo(String value) {
            addCriterion("x00281050 >=", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050LessThan(String value) {
            addCriterion("x00281050 <", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050LessThanOrEqualTo(String value) {
            addCriterion("x00281050 <=", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050Like(String value) {
            addCriterion("x00281050 like", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050NotLike(String value) {
            addCriterion("x00281050 not like", value, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050In(List<String> values) {
            addCriterion("x00281050 in", values, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050NotIn(List<String> values) {
            addCriterion("x00281050 not in", values, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050Between(String value1, String value2) {
            addCriterion("x00281050 between", value1, value2, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281050NotBetween(String value1, String value2) {
            addCriterion("x00281050 not between", value1, value2, "x00281050");
            return (Criteria) this;
        }

        public Criteria andX00281051IsNull() {
            addCriterion("x00281051 is null");
            return (Criteria) this;
        }

        public Criteria andX00281051IsNotNull() {
            addCriterion("x00281051 is not null");
            return (Criteria) this;
        }

        public Criteria andX00281051EqualTo(String value) {
            addCriterion("x00281051 =", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051NotEqualTo(String value) {
            addCriterion("x00281051 <>", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051GreaterThan(String value) {
            addCriterion("x00281051 >", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051GreaterThanOrEqualTo(String value) {
            addCriterion("x00281051 >=", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051LessThan(String value) {
            addCriterion("x00281051 <", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051LessThanOrEqualTo(String value) {
            addCriterion("x00281051 <=", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051Like(String value) {
            addCriterion("x00281051 like", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051NotLike(String value) {
            addCriterion("x00281051 not like", value, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051In(List<String> values) {
            addCriterion("x00281051 in", values, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051NotIn(List<String> values) {
            addCriterion("x00281051 not in", values, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051Between(String value1, String value2) {
            addCriterion("x00281051 between", value1, value2, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX00281051NotBetween(String value1, String value2) {
            addCriterion("x00281051 not between", value1, value2, "x00281051");
            return (Criteria) this;
        }

        public Criteria andX0040a491IsNull() {
            addCriterion("x0040A491 is null");
            return (Criteria) this;
        }

        public Criteria andX0040a491IsNotNull() {
            addCriterion("x0040A491 is not null");
            return (Criteria) this;
        }

        public Criteria andX0040a491EqualTo(String value) {
            addCriterion("x0040A491 =", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491NotEqualTo(String value) {
            addCriterion("x0040A491 <>", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491GreaterThan(String value) {
            addCriterion("x0040A491 >", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491GreaterThanOrEqualTo(String value) {
            addCriterion("x0040A491 >=", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491LessThan(String value) {
            addCriterion("x0040A491 <", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491LessThanOrEqualTo(String value) {
            addCriterion("x0040A491 <=", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491Like(String value) {
            addCriterion("x0040A491 like", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491NotLike(String value) {
            addCriterion("x0040A491 not like", value, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491In(List<String> values) {
            addCriterion("x0040A491 in", values, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491NotIn(List<String> values) {
            addCriterion("x0040A491 not in", values, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491Between(String value1, String value2) {
            addCriterion("x0040A491 between", value1, value2, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a491NotBetween(String value1, String value2) {
            addCriterion("x0040A491 not between", value1, value2, "x0040a491");
            return (Criteria) this;
        }

        public Criteria andX0040a493IsNull() {
            addCriterion("x0040A493 is null");
            return (Criteria) this;
        }

        public Criteria andX0040a493IsNotNull() {
            addCriterion("x0040A493 is not null");
            return (Criteria) this;
        }

        public Criteria andX0040a493EqualTo(String value) {
            addCriterion("x0040A493 =", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493NotEqualTo(String value) {
            addCriterion("x0040A493 <>", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493GreaterThan(String value) {
            addCriterion("x0040A493 >", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493GreaterThanOrEqualTo(String value) {
            addCriterion("x0040A493 >=", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493LessThan(String value) {
            addCriterion("x0040A493 <", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493LessThanOrEqualTo(String value) {
            addCriterion("x0040A493 <=", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493Like(String value) {
            addCriterion("x0040A493 like", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493NotLike(String value) {
            addCriterion("x0040A493 not like", value, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493In(List<String> values) {
            addCriterion("x0040A493 in", values, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493NotIn(List<String> values) {
            addCriterion("x0040A493 not in", values, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493Between(String value1, String value2) {
            addCriterion("x0040A493 between", value1, value2, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andX0040a493NotBetween(String value1, String value2) {
            addCriterion("x0040A493 not between", value1, value2, "x0040a493");
            return (Criteria) this;
        }

        public Criteria andJsonIsNull() {
            addCriterion("json is null");
            return (Criteria) this;
        }

        public Criteria andJsonIsNotNull() {
            addCriterion("json is not null");
            return (Criteria) this;
        }

        public Criteria andJsonEqualTo(Object value) {
            addCriterion("json =", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotEqualTo(Object value) {
            addCriterion("json <>", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThan(Object value) {
            addCriterion("json >", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThanOrEqualTo(Object value) {
            addCriterion("json >=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThan(Object value) {
            addCriterion("json <", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThanOrEqualTo(Object value) {
            addCriterion("json <=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonIn(List<Object> values) {
            addCriterion("json in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotIn(List<Object> values) {
            addCriterion("json not in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonBetween(Object value1, Object value2) {
            addCriterion("json between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotBetween(Object value1, Object value2) {
            addCriterion("json not between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNull() {
            addCriterion("createdAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNotNull() {
            addCriterion("createdAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedatEqualTo(Date value) {
            addCriterion("createdAt =", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotEqualTo(Date value) {
            addCriterion("createdAt <>", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThan(Date value) {
            addCriterion("createdAt >", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("createdAt >=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThan(Date value) {
            addCriterion("createdAt <", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThanOrEqualTo(Date value) {
            addCriterion("createdAt <=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatIn(List<Date> values) {
            addCriterion("createdAt in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotIn(List<Date> values) {
            addCriterion("createdAt not in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatBetween(Date value1, Date value2) {
            addCriterion("createdAt between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotBetween(Date value1, Date value2) {
            addCriterion("createdAt not between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNull() {
            addCriterion("updatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNotNull() {
            addCriterion("updatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatEqualTo(Date value) {
            addCriterion("updatedAt =", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotEqualTo(Date value) {
            addCriterion("updatedAt <>", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThan(Date value) {
            addCriterion("updatedAt >", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedAt >=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThan(Date value) {
            addCriterion("updatedAt <", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThanOrEqualTo(Date value) {
            addCriterion("updatedAt <=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIn(List<Date> values) {
            addCriterion("updatedAt in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotIn(List<Date> values) {
            addCriterion("updatedAt not in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatBetween(Date value1, Date value2) {
            addCriterion("updatedAt between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotBetween(Date value1, Date value2) {
            addCriterion("updatedAt not between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIsNull() {
            addCriterion("deleteStatus is null");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIsNotNull() {
            addCriterion("deleteStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeletestatusEqualTo(Integer value) {
            addCriterion("deleteStatus =", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotEqualTo(Integer value) {
            addCriterion("deleteStatus <>", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusGreaterThan(Integer value) {
            addCriterion("deleteStatus >", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteStatus >=", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusLessThan(Integer value) {
            addCriterion("deleteStatus <", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusLessThanOrEqualTo(Integer value) {
            addCriterion("deleteStatus <=", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIn(List<Integer> values) {
            addCriterion("deleteStatus in", values, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotIn(List<Integer> values) {
            addCriterion("deleteStatus not in", values, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusBetween(Integer value1, Integer value2) {
            addCriterion("deleteStatus between", value1, value2, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteStatus not between", value1, value2, "deletestatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Instance
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}