package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

public class OperatorsnameKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.OperatorsName.x0020000E
     *
     * @mbg.generated
     */
    private String x0020000e;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.OperatorsName.PersonNameId
     *
     * @mbg.generated
     */
    private Integer personnameid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.OperatorsName.x0020000E
     *
     * @return the value of public.OperatorsName.x0020000E
     *
     * @mbg.generated
     */
    public String getX0020000e() {
        return x0020000e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.OperatorsName.x0020000E
     *
     * @param x0020000e the value for public.OperatorsName.x0020000E
     *
     * @mbg.generated
     */
    public void setX0020000e(String x0020000e) {
        this.x0020000e = x0020000e == null ? null : x0020000e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.OperatorsName.PersonNameId
     *
     * @return the value of public.OperatorsName.PersonNameId
     *
     * @mbg.generated
     */
    public Integer getPersonnameid() {
        return personnameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.OperatorsName.PersonNameId
     *
     * @param personnameid the value for public.OperatorsName.PersonNameId
     *
     * @mbg.generated
     */
    public void setPersonnameid(Integer personnameid) {
        this.personnameid = personnameid;
    }
}