package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00100010
     *
     * @mbg.generated
     */
    private Integer x00100010;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00100020
     *
     * @mbg.generated
     */
    private String x00100020;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00100021
     *
     * @mbg.generated
     */
    private String x00100021;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00100030
     *
     * @mbg.generated
     */
    private Date x00100030;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00100032
     *
     * @mbg.generated
     */
    private Short x00100032;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00100040
     *
     * @mbg.generated
     */
    private String x00100040;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00102160
     *
     * @mbg.generated
     */
    private String x00102160;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00104000
     *
     * @mbg.generated
     */
    private String x00104000;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00880130
     *
     * @mbg.generated
     */
    private String x00880130;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.x00880140
     *
     * @mbg.generated
     */
    private String x00880140;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.json
     *
     * @mbg.generated
     */
    private Object json;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Patient.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.id
     *
     * @return the value of public.Patient.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.id
     *
     * @param id the value for public.Patient.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00100010
     *
     * @return the value of public.Patient.x00100010
     *
     * @mbg.generated
     */
    public Integer getX00100010() {
        return x00100010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00100010
     *
     * @param x00100010 the value for public.Patient.x00100010
     *
     * @mbg.generated
     */
    public void setX00100010(Integer x00100010) {
        this.x00100010 = x00100010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00100020
     *
     * @return the value of public.Patient.x00100020
     *
     * @mbg.generated
     */
    public String getX00100020() {
        return x00100020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00100020
     *
     * @param x00100020 the value for public.Patient.x00100020
     *
     * @mbg.generated
     */
    public void setX00100020(String x00100020) {
        this.x00100020 = x00100020 == null ? null : x00100020.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00100021
     *
     * @return the value of public.Patient.x00100021
     *
     * @mbg.generated
     */
    public String getX00100021() {
        return x00100021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00100021
     *
     * @param x00100021 the value for public.Patient.x00100021
     *
     * @mbg.generated
     */
    public void setX00100021(String x00100021) {
        this.x00100021 = x00100021 == null ? null : x00100021.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00100030
     *
     * @return the value of public.Patient.x00100030
     *
     * @mbg.generated
     */
    public Date getX00100030() {
        return x00100030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00100030
     *
     * @param x00100030 the value for public.Patient.x00100030
     *
     * @mbg.generated
     */
    public void setX00100030(Date x00100030) {
        this.x00100030 = x00100030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00100032
     *
     * @return the value of public.Patient.x00100032
     *
     * @mbg.generated
     */
    public Short getX00100032() {
        return x00100032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00100032
     *
     * @param x00100032 the value for public.Patient.x00100032
     *
     * @mbg.generated
     */
    public void setX00100032(Short x00100032) {
        this.x00100032 = x00100032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00100040
     *
     * @return the value of public.Patient.x00100040
     *
     * @mbg.generated
     */
    public String getX00100040() {
        return x00100040;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00100040
     *
     * @param x00100040 the value for public.Patient.x00100040
     *
     * @mbg.generated
     */
    public void setX00100040(String x00100040) {
        this.x00100040 = x00100040 == null ? null : x00100040.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00102160
     *
     * @return the value of public.Patient.x00102160
     *
     * @mbg.generated
     */
    public String getX00102160() {
        return x00102160;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00102160
     *
     * @param x00102160 the value for public.Patient.x00102160
     *
     * @mbg.generated
     */
    public void setX00102160(String x00102160) {
        this.x00102160 = x00102160 == null ? null : x00102160.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00104000
     *
     * @return the value of public.Patient.x00104000
     *
     * @mbg.generated
     */
    public String getX00104000() {
        return x00104000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00104000
     *
     * @param x00104000 the value for public.Patient.x00104000
     *
     * @mbg.generated
     */
    public void setX00104000(String x00104000) {
        this.x00104000 = x00104000 == null ? null : x00104000.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00880130
     *
     * @return the value of public.Patient.x00880130
     *
     * @mbg.generated
     */
    public String getX00880130() {
        return x00880130;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00880130
     *
     * @param x00880130 the value for public.Patient.x00880130
     *
     * @mbg.generated
     */
    public void setX00880130(String x00880130) {
        this.x00880130 = x00880130 == null ? null : x00880130.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.x00880140
     *
     * @return the value of public.Patient.x00880140
     *
     * @mbg.generated
     */
    public String getX00880140() {
        return x00880140;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.x00880140
     *
     * @param x00880140 the value for public.Patient.x00880140
     *
     * @mbg.generated
     */
    public void setX00880140(String x00880140) {
        this.x00880140 = x00880140 == null ? null : x00880140.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.json
     *
     * @return the value of public.Patient.json
     *
     * @mbg.generated
     */
    public Object getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.json
     *
     * @param json the value for public.Patient.json
     *
     * @mbg.generated
     */
    public void setJson(Object json) {
        this.json = json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.createdAt
     *
     * @return the value of public.Patient.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.createdAt
     *
     * @param createdat the value for public.Patient.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Patient.updatedAt
     *
     * @return the value of public.Patient.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Patient.updatedAt
     *
     * @param updatedat the value for public.Patient.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}