package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PatientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public PatientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andX00100010IsNull() {
            addCriterion("x00100010 is null");
            return (Criteria) this;
        }

        public Criteria andX00100010IsNotNull() {
            addCriterion("x00100010 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100010EqualTo(Integer value) {
            addCriterion("x00100010 =", value, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010NotEqualTo(Integer value) {
            addCriterion("x00100010 <>", value, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010GreaterThan(Integer value) {
            addCriterion("x00100010 >", value, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010GreaterThanOrEqualTo(Integer value) {
            addCriterion("x00100010 >=", value, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010LessThan(Integer value) {
            addCriterion("x00100010 <", value, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010LessThanOrEqualTo(Integer value) {
            addCriterion("x00100010 <=", value, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010In(List<Integer> values) {
            addCriterion("x00100010 in", values, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010NotIn(List<Integer> values) {
            addCriterion("x00100010 not in", values, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010Between(Integer value1, Integer value2) {
            addCriterion("x00100010 between", value1, value2, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100010NotBetween(Integer value1, Integer value2) {
            addCriterion("x00100010 not between", value1, value2, "x00100010");
            return (Criteria) this;
        }

        public Criteria andX00100020IsNull() {
            addCriterion("x00100020 is null");
            return (Criteria) this;
        }

        public Criteria andX00100020IsNotNull() {
            addCriterion("x00100020 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100020EqualTo(String value) {
            addCriterion("x00100020 =", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotEqualTo(String value) {
            addCriterion("x00100020 <>", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020GreaterThan(String value) {
            addCriterion("x00100020 >", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020GreaterThanOrEqualTo(String value) {
            addCriterion("x00100020 >=", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020LessThan(String value) {
            addCriterion("x00100020 <", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020LessThanOrEqualTo(String value) {
            addCriterion("x00100020 <=", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020Like(String value) {
            addCriterion("x00100020 like", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotLike(String value) {
            addCriterion("x00100020 not like", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020In(List<String> values) {
            addCriterion("x00100020 in", values, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotIn(List<String> values) {
            addCriterion("x00100020 not in", values, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020Between(String value1, String value2) {
            addCriterion("x00100020 between", value1, value2, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotBetween(String value1, String value2) {
            addCriterion("x00100020 not between", value1, value2, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100021IsNull() {
            addCriterion("x00100021 is null");
            return (Criteria) this;
        }

        public Criteria andX00100021IsNotNull() {
            addCriterion("x00100021 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100021EqualTo(String value) {
            addCriterion("x00100021 =", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021NotEqualTo(String value) {
            addCriterion("x00100021 <>", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021GreaterThan(String value) {
            addCriterion("x00100021 >", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021GreaterThanOrEqualTo(String value) {
            addCriterion("x00100021 >=", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021LessThan(String value) {
            addCriterion("x00100021 <", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021LessThanOrEqualTo(String value) {
            addCriterion("x00100021 <=", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021Like(String value) {
            addCriterion("x00100021 like", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021NotLike(String value) {
            addCriterion("x00100021 not like", value, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021In(List<String> values) {
            addCriterion("x00100021 in", values, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021NotIn(List<String> values) {
            addCriterion("x00100021 not in", values, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021Between(String value1, String value2) {
            addCriterion("x00100021 between", value1, value2, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100021NotBetween(String value1, String value2) {
            addCriterion("x00100021 not between", value1, value2, "x00100021");
            return (Criteria) this;
        }

        public Criteria andX00100030IsNull() {
            addCriterion("x00100030 is null");
            return (Criteria) this;
        }

        public Criteria andX00100030IsNotNull() {
            addCriterion("x00100030 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100030EqualTo(Date value) {
            addCriterionForJDBCDate("x00100030 =", value, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030NotEqualTo(Date value) {
            addCriterionForJDBCDate("x00100030 <>", value, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030GreaterThan(Date value) {
            addCriterionForJDBCDate("x00100030 >", value, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00100030 >=", value, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030LessThan(Date value) {
            addCriterionForJDBCDate("x00100030 <", value, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00100030 <=", value, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030In(List<Date> values) {
            addCriterionForJDBCDate("x00100030 in", values, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030NotIn(List<Date> values) {
            addCriterionForJDBCDate("x00100030 not in", values, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030Between(Date value1, Date value2) {
            addCriterionForJDBCDate("x00100030 between", value1, value2, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100030NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("x00100030 not between", value1, value2, "x00100030");
            return (Criteria) this;
        }

        public Criteria andX00100032IsNull() {
            addCriterion("x00100032 is null");
            return (Criteria) this;
        }

        public Criteria andX00100032IsNotNull() {
            addCriterion("x00100032 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100032EqualTo(Short value) {
            addCriterion("x00100032 =", value, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032NotEqualTo(Short value) {
            addCriterion("x00100032 <>", value, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032GreaterThan(Short value) {
            addCriterion("x00100032 >", value, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032GreaterThanOrEqualTo(Short value) {
            addCriterion("x00100032 >=", value, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032LessThan(Short value) {
            addCriterion("x00100032 <", value, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032LessThanOrEqualTo(Short value) {
            addCriterion("x00100032 <=", value, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032In(List<Short> values) {
            addCriterion("x00100032 in", values, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032NotIn(List<Short> values) {
            addCriterion("x00100032 not in", values, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032Between(Short value1, Short value2) {
            addCriterion("x00100032 between", value1, value2, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100032NotBetween(Short value1, Short value2) {
            addCriterion("x00100032 not between", value1, value2, "x00100032");
            return (Criteria) this;
        }

        public Criteria andX00100040IsNull() {
            addCriterion("x00100040 is null");
            return (Criteria) this;
        }

        public Criteria andX00100040IsNotNull() {
            addCriterion("x00100040 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100040EqualTo(String value) {
            addCriterion("x00100040 =", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040NotEqualTo(String value) {
            addCriterion("x00100040 <>", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040GreaterThan(String value) {
            addCriterion("x00100040 >", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040GreaterThanOrEqualTo(String value) {
            addCriterion("x00100040 >=", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040LessThan(String value) {
            addCriterion("x00100040 <", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040LessThanOrEqualTo(String value) {
            addCriterion("x00100040 <=", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040Like(String value) {
            addCriterion("x00100040 like", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040NotLike(String value) {
            addCriterion("x00100040 not like", value, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040In(List<String> values) {
            addCriterion("x00100040 in", values, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040NotIn(List<String> values) {
            addCriterion("x00100040 not in", values, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040Between(String value1, String value2) {
            addCriterion("x00100040 between", value1, value2, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00100040NotBetween(String value1, String value2) {
            addCriterion("x00100040 not between", value1, value2, "x00100040");
            return (Criteria) this;
        }

        public Criteria andX00102160IsNull() {
            addCriterion("x00102160 is null");
            return (Criteria) this;
        }

        public Criteria andX00102160IsNotNull() {
            addCriterion("x00102160 is not null");
            return (Criteria) this;
        }

        public Criteria andX00102160EqualTo(String value) {
            addCriterion("x00102160 =", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160NotEqualTo(String value) {
            addCriterion("x00102160 <>", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160GreaterThan(String value) {
            addCriterion("x00102160 >", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160GreaterThanOrEqualTo(String value) {
            addCriterion("x00102160 >=", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160LessThan(String value) {
            addCriterion("x00102160 <", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160LessThanOrEqualTo(String value) {
            addCriterion("x00102160 <=", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160Like(String value) {
            addCriterion("x00102160 like", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160NotLike(String value) {
            addCriterion("x00102160 not like", value, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160In(List<String> values) {
            addCriterion("x00102160 in", values, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160NotIn(List<String> values) {
            addCriterion("x00102160 not in", values, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160Between(String value1, String value2) {
            addCriterion("x00102160 between", value1, value2, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00102160NotBetween(String value1, String value2) {
            addCriterion("x00102160 not between", value1, value2, "x00102160");
            return (Criteria) this;
        }

        public Criteria andX00104000IsNull() {
            addCriterion("x00104000 is null");
            return (Criteria) this;
        }

        public Criteria andX00104000IsNotNull() {
            addCriterion("x00104000 is not null");
            return (Criteria) this;
        }

        public Criteria andX00104000EqualTo(String value) {
            addCriterion("x00104000 =", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000NotEqualTo(String value) {
            addCriterion("x00104000 <>", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000GreaterThan(String value) {
            addCriterion("x00104000 >", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000GreaterThanOrEqualTo(String value) {
            addCriterion("x00104000 >=", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000LessThan(String value) {
            addCriterion("x00104000 <", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000LessThanOrEqualTo(String value) {
            addCriterion("x00104000 <=", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000Like(String value) {
            addCriterion("x00104000 like", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000NotLike(String value) {
            addCriterion("x00104000 not like", value, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000In(List<String> values) {
            addCriterion("x00104000 in", values, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000NotIn(List<String> values) {
            addCriterion("x00104000 not in", values, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000Between(String value1, String value2) {
            addCriterion("x00104000 between", value1, value2, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00104000NotBetween(String value1, String value2) {
            addCriterion("x00104000 not between", value1, value2, "x00104000");
            return (Criteria) this;
        }

        public Criteria andX00880130IsNull() {
            addCriterion("x00880130 is null");
            return (Criteria) this;
        }

        public Criteria andX00880130IsNotNull() {
            addCriterion("x00880130 is not null");
            return (Criteria) this;
        }

        public Criteria andX00880130EqualTo(String value) {
            addCriterion("x00880130 =", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130NotEqualTo(String value) {
            addCriterion("x00880130 <>", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130GreaterThan(String value) {
            addCriterion("x00880130 >", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130GreaterThanOrEqualTo(String value) {
            addCriterion("x00880130 >=", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130LessThan(String value) {
            addCriterion("x00880130 <", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130LessThanOrEqualTo(String value) {
            addCriterion("x00880130 <=", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130Like(String value) {
            addCriterion("x00880130 like", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130NotLike(String value) {
            addCriterion("x00880130 not like", value, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130In(List<String> values) {
            addCriterion("x00880130 in", values, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130NotIn(List<String> values) {
            addCriterion("x00880130 not in", values, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130Between(String value1, String value2) {
            addCriterion("x00880130 between", value1, value2, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880130NotBetween(String value1, String value2) {
            addCriterion("x00880130 not between", value1, value2, "x00880130");
            return (Criteria) this;
        }

        public Criteria andX00880140IsNull() {
            addCriterion("x00880140 is null");
            return (Criteria) this;
        }

        public Criteria andX00880140IsNotNull() {
            addCriterion("x00880140 is not null");
            return (Criteria) this;
        }

        public Criteria andX00880140EqualTo(String value) {
            addCriterion("x00880140 =", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140NotEqualTo(String value) {
            addCriterion("x00880140 <>", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140GreaterThan(String value) {
            addCriterion("x00880140 >", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140GreaterThanOrEqualTo(String value) {
            addCriterion("x00880140 >=", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140LessThan(String value) {
            addCriterion("x00880140 <", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140LessThanOrEqualTo(String value) {
            addCriterion("x00880140 <=", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140Like(String value) {
            addCriterion("x00880140 like", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140NotLike(String value) {
            addCriterion("x00880140 not like", value, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140In(List<String> values) {
            addCriterion("x00880140 in", values, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140NotIn(List<String> values) {
            addCriterion("x00880140 not in", values, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140Between(String value1, String value2) {
            addCriterion("x00880140 between", value1, value2, "x00880140");
            return (Criteria) this;
        }

        public Criteria andX00880140NotBetween(String value1, String value2) {
            addCriterion("x00880140 not between", value1, value2, "x00880140");
            return (Criteria) this;
        }

        public Criteria andJsonIsNull() {
            addCriterion("json is null");
            return (Criteria) this;
        }

        public Criteria andJsonIsNotNull() {
            addCriterion("json is not null");
            return (Criteria) this;
        }

        public Criteria andJsonEqualTo(Object value) {
            addCriterion("json =", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotEqualTo(Object value) {
            addCriterion("json <>", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThan(Object value) {
            addCriterion("json >", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThanOrEqualTo(Object value) {
            addCriterion("json >=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThan(Object value) {
            addCriterion("json <", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThanOrEqualTo(Object value) {
            addCriterion("json <=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonIn(List<Object> values) {
            addCriterion("json in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotIn(List<Object> values) {
            addCriterion("json not in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonBetween(Object value1, Object value2) {
            addCriterion("json between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotBetween(Object value1, Object value2) {
            addCriterion("json not between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNull() {
            addCriterion("createdAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNotNull() {
            addCriterion("createdAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedatEqualTo(Date value) {
            addCriterion("createdAt =", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotEqualTo(Date value) {
            addCriterion("createdAt <>", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThan(Date value) {
            addCriterion("createdAt >", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("createdAt >=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThan(Date value) {
            addCriterion("createdAt <", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThanOrEqualTo(Date value) {
            addCriterion("createdAt <=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatIn(List<Date> values) {
            addCriterion("createdAt in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotIn(List<Date> values) {
            addCriterion("createdAt not in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatBetween(Date value1, Date value2) {
            addCriterion("createdAt between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotBetween(Date value1, Date value2) {
            addCriterion("createdAt not between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNull() {
            addCriterion("updatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNotNull() {
            addCriterion("updatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatEqualTo(Date value) {
            addCriterion("updatedAt =", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotEqualTo(Date value) {
            addCriterion("updatedAt <>", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThan(Date value) {
            addCriterion("updatedAt >", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedAt >=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThan(Date value) {
            addCriterion("updatedAt <", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThanOrEqualTo(Date value) {
            addCriterion("updatedAt <=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIn(List<Date> values) {
            addCriterion("updatedAt in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotIn(List<Date> values) {
            addCriterion("updatedAt not in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatBetween(Date value1, Date value2) {
            addCriterion("updatedAt between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotBetween(Date value1, Date value2) {
            addCriterion("updatedAt not between", value1, value2, "updatedat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Patient
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}