package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Personname {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.PersonName.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.PersonName.alphabetic
     *
     * @mbg.generated
     */
    private String alphabetic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.PersonName.ideographic
     *
     * @mbg.generated
     */
    private String ideographic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.PersonName.phonetic
     *
     * @mbg.generated
     */
    private String phonetic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.PersonName.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.PersonName.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.PersonName.id
     *
     * @return the value of public.PersonName.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.PersonName.id
     *
     * @param id the value for public.PersonName.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.PersonName.alphabetic
     *
     * @return the value of public.PersonName.alphabetic
     *
     * @mbg.generated
     */
    public String getAlphabetic() {
        return alphabetic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.PersonName.alphabetic
     *
     * @param alphabetic the value for public.PersonName.alphabetic
     *
     * @mbg.generated
     */
    public void setAlphabetic(String alphabetic) {
        this.alphabetic = alphabetic == null ? null : alphabetic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.PersonName.ideographic
     *
     * @return the value of public.PersonName.ideographic
     *
     * @mbg.generated
     */
    public String getIdeographic() {
        return ideographic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.PersonName.ideographic
     *
     * @param ideographic the value for public.PersonName.ideographic
     *
     * @mbg.generated
     */
    public void setIdeographic(String ideographic) {
        this.ideographic = ideographic == null ? null : ideographic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.PersonName.phonetic
     *
     * @return the value of public.PersonName.phonetic
     *
     * @mbg.generated
     */
    public String getPhonetic() {
        return phonetic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.PersonName.phonetic
     *
     * @param phonetic the value for public.PersonName.phonetic
     *
     * @mbg.generated
     */
    public void setPhonetic(String phonetic) {
        this.phonetic = phonetic == null ? null : phonetic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.PersonName.createdAt
     *
     * @return the value of public.PersonName.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.PersonName.createdAt
     *
     * @param createdat the value for public.PersonName.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.PersonName.updatedAt
     *
     * @return the value of public.PersonName.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.PersonName.updatedAt
     *
     * @param updatedat the value for public.PersonName.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}