package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SeriesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public SeriesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andX0020000eIsNull() {
            addCriterion("x0020000E is null");
            return (Criteria) this;
        }

        public Criteria andX0020000eIsNotNull() {
            addCriterion("x0020000E is not null");
            return (Criteria) this;
        }

        public Criteria andX0020000eEqualTo(String value) {
            addCriterion("x0020000E =", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotEqualTo(String value) {
            addCriterion("x0020000E <>", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eGreaterThan(String value) {
            addCriterion("x0020000E >", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eGreaterThanOrEqualTo(String value) {
            addCriterion("x0020000E >=", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eLessThan(String value) {
            addCriterion("x0020000E <", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eLessThanOrEqualTo(String value) {
            addCriterion("x0020000E <=", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eLike(String value) {
            addCriterion("x0020000E like", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotLike(String value) {
            addCriterion("x0020000E not like", value, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eIn(List<String> values) {
            addCriterion("x0020000E in", values, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotIn(List<String> values) {
            addCriterion("x0020000E not in", values, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eBetween(String value1, String value2) {
            addCriterion("x0020000E between", value1, value2, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andX0020000eNotBetween(String value1, String value2) {
            addCriterion("x0020000E not between", value1, value2, "x0020000e");
            return (Criteria) this;
        }

        public Criteria andSeriespathIsNull() {
            addCriterion("seriesPath is null");
            return (Criteria) this;
        }

        public Criteria andSeriespathIsNotNull() {
            addCriterion("seriesPath is not null");
            return (Criteria) this;
        }

        public Criteria andSeriespathEqualTo(String value) {
            addCriterion("seriesPath =", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathNotEqualTo(String value) {
            addCriterion("seriesPath <>", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathGreaterThan(String value) {
            addCriterion("seriesPath >", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathGreaterThanOrEqualTo(String value) {
            addCriterion("seriesPath >=", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathLessThan(String value) {
            addCriterion("seriesPath <", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathLessThanOrEqualTo(String value) {
            addCriterion("seriesPath <=", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathLike(String value) {
            addCriterion("seriesPath like", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathNotLike(String value) {
            addCriterion("seriesPath not like", value, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathIn(List<String> values) {
            addCriterion("seriesPath in", values, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathNotIn(List<String> values) {
            addCriterion("seriesPath not in", values, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathBetween(String value1, String value2) {
            addCriterion("seriesPath between", value1, value2, "seriespath");
            return (Criteria) this;
        }

        public Criteria andSeriespathNotBetween(String value1, String value2) {
            addCriterion("seriesPath not between", value1, value2, "seriespath");
            return (Criteria) this;
        }

        public Criteria andX0020000dIsNull() {
            addCriterion("x0020000D is null");
            return (Criteria) this;
        }

        public Criteria andX0020000dIsNotNull() {
            addCriterion("x0020000D is not null");
            return (Criteria) this;
        }

        public Criteria andX0020000dEqualTo(String value) {
            addCriterion("x0020000D =", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotEqualTo(String value) {
            addCriterion("x0020000D <>", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dGreaterThan(String value) {
            addCriterion("x0020000D >", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dGreaterThanOrEqualTo(String value) {
            addCriterion("x0020000D >=", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLessThan(String value) {
            addCriterion("x0020000D <", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLessThanOrEqualTo(String value) {
            addCriterion("x0020000D <=", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLike(String value) {
            addCriterion("x0020000D like", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotLike(String value) {
            addCriterion("x0020000D not like", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dIn(List<String> values) {
            addCriterion("x0020000D in", values, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotIn(List<String> values) {
            addCriterion("x0020000D not in", values, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dBetween(String value1, String value2) {
            addCriterion("x0020000D between", value1, value2, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotBetween(String value1, String value2) {
            addCriterion("x0020000D not between", value1, value2, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX00080021IsNull() {
            addCriterion("x00080021 is null");
            return (Criteria) this;
        }

        public Criteria andX00080021IsNotNull() {
            addCriterion("x00080021 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080021EqualTo(Date value) {
            addCriterionForJDBCDate("x00080021 =", value, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021NotEqualTo(Date value) {
            addCriterionForJDBCDate("x00080021 <>", value, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021GreaterThan(Date value) {
            addCriterionForJDBCDate("x00080021 >", value, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00080021 >=", value, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021LessThan(Date value) {
            addCriterionForJDBCDate("x00080021 <", value, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00080021 <=", value, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021In(List<Date> values) {
            addCriterionForJDBCDate("x00080021 in", values, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021NotIn(List<Date> values) {
            addCriterionForJDBCDate("x00080021 not in", values, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021Between(Date value1, Date value2) {
            addCriterionForJDBCDate("x00080021 between", value1, value2, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080021NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("x00080021 not between", value1, value2, "x00080021");
            return (Criteria) this;
        }

        public Criteria andX00080060IsNull() {
            addCriterion("x00080060 is null");
            return (Criteria) this;
        }

        public Criteria andX00080060IsNotNull() {
            addCriterion("x00080060 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080060EqualTo(String value) {
            addCriterion("x00080060 =", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060NotEqualTo(String value) {
            addCriterion("x00080060 <>", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060GreaterThan(String value) {
            addCriterion("x00080060 >", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060GreaterThanOrEqualTo(String value) {
            addCriterion("x00080060 >=", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060LessThan(String value) {
            addCriterion("x00080060 <", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060LessThanOrEqualTo(String value) {
            addCriterion("x00080060 <=", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060Like(String value) {
            addCriterion("x00080060 like", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060NotLike(String value) {
            addCriterion("x00080060 not like", value, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060In(List<String> values) {
            addCriterion("x00080060 in", values, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060NotIn(List<String> values) {
            addCriterion("x00080060 not in", values, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060Between(String value1, String value2) {
            addCriterion("x00080060 between", value1, value2, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX00080060NotBetween(String value1, String value2) {
            addCriterion("x00080060 not between", value1, value2, "x00080060");
            return (Criteria) this;
        }

        public Criteria andX0008103eIsNull() {
            addCriterion("x0008103E is null");
            return (Criteria) this;
        }

        public Criteria andX0008103eIsNotNull() {
            addCriterion("x0008103E is not null");
            return (Criteria) this;
        }

        public Criteria andX0008103eEqualTo(String value) {
            addCriterion("x0008103E =", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eNotEqualTo(String value) {
            addCriterion("x0008103E <>", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eGreaterThan(String value) {
            addCriterion("x0008103E >", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eGreaterThanOrEqualTo(String value) {
            addCriterion("x0008103E >=", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eLessThan(String value) {
            addCriterion("x0008103E <", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eLessThanOrEqualTo(String value) {
            addCriterion("x0008103E <=", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eLike(String value) {
            addCriterion("x0008103E like", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eNotLike(String value) {
            addCriterion("x0008103E not like", value, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eIn(List<String> values) {
            addCriterion("x0008103E in", values, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eNotIn(List<String> values) {
            addCriterion("x0008103E not in", values, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eBetween(String value1, String value2) {
            addCriterion("x0008103E between", value1, value2, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103eNotBetween(String value1, String value2) {
            addCriterion("x0008103E not between", value1, value2, "x0008103e");
            return (Criteria) this;
        }

        public Criteria andX0008103fIsNull() {
            addCriterion("x0008103F is null");
            return (Criteria) this;
        }

        public Criteria andX0008103fIsNotNull() {
            addCriterion("x0008103F is not null");
            return (Criteria) this;
        }

        public Criteria andX0008103fEqualTo(Object value) {
            addCriterion("x0008103F =", value, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fNotEqualTo(Object value) {
            addCriterion("x0008103F <>", value, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fGreaterThan(Object value) {
            addCriterion("x0008103F >", value, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fGreaterThanOrEqualTo(Object value) {
            addCriterion("x0008103F >=", value, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fLessThan(Object value) {
            addCriterion("x0008103F <", value, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fLessThanOrEqualTo(Object value) {
            addCriterion("x0008103F <=", value, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fIn(List<Object> values) {
            addCriterion("x0008103F in", values, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fNotIn(List<Object> values) {
            addCriterion("x0008103F not in", values, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fBetween(Object value1, Object value2) {
            addCriterion("x0008103F between", value1, value2, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX0008103fNotBetween(Object value1, Object value2) {
            addCriterion("x0008103F not between", value1, value2, "x0008103f");
            return (Criteria) this;
        }

        public Criteria andX00081052IsNull() {
            addCriterion("x00081052 is null");
            return (Criteria) this;
        }

        public Criteria andX00081052IsNotNull() {
            addCriterion("x00081052 is not null");
            return (Criteria) this;
        }

        public Criteria andX00081052EqualTo(Object value) {
            addCriterion("x00081052 =", value, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052NotEqualTo(Object value) {
            addCriterion("x00081052 <>", value, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052GreaterThan(Object value) {
            addCriterion("x00081052 >", value, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052GreaterThanOrEqualTo(Object value) {
            addCriterion("x00081052 >=", value, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052LessThan(Object value) {
            addCriterion("x00081052 <", value, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052LessThanOrEqualTo(Object value) {
            addCriterion("x00081052 <=", value, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052In(List<Object> values) {
            addCriterion("x00081052 in", values, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052NotIn(List<Object> values) {
            addCriterion("x00081052 not in", values, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052Between(Object value1, Object value2) {
            addCriterion("x00081052 between", value1, value2, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081052NotBetween(Object value1, Object value2) {
            addCriterion("x00081052 not between", value1, value2, "x00081052");
            return (Criteria) this;
        }

        public Criteria andX00081072IsNull() {
            addCriterion("x00081072 is null");
            return (Criteria) this;
        }

        public Criteria andX00081072IsNotNull() {
            addCriterion("x00081072 is not null");
            return (Criteria) this;
        }

        public Criteria andX00081072EqualTo(Object value) {
            addCriterion("x00081072 =", value, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072NotEqualTo(Object value) {
            addCriterion("x00081072 <>", value, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072GreaterThan(Object value) {
            addCriterion("x00081072 >", value, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072GreaterThanOrEqualTo(Object value) {
            addCriterion("x00081072 >=", value, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072LessThan(Object value) {
            addCriterion("x00081072 <", value, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072LessThanOrEqualTo(Object value) {
            addCriterion("x00081072 <=", value, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072In(List<Object> values) {
            addCriterion("x00081072 in", values, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072NotIn(List<Object> values) {
            addCriterion("x00081072 not in", values, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072Between(Object value1, Object value2) {
            addCriterion("x00081072 between", value1, value2, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081072NotBetween(Object value1, Object value2) {
            addCriterion("x00081072 not between", value1, value2, "x00081072");
            return (Criteria) this;
        }

        public Criteria andX00081250IsNull() {
            addCriterion("x00081250 is null");
            return (Criteria) this;
        }

        public Criteria andX00081250IsNotNull() {
            addCriterion("x00081250 is not null");
            return (Criteria) this;
        }

        public Criteria andX00081250EqualTo(Object value) {
            addCriterion("x00081250 =", value, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250NotEqualTo(Object value) {
            addCriterion("x00081250 <>", value, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250GreaterThan(Object value) {
            addCriterion("x00081250 >", value, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250GreaterThanOrEqualTo(Object value) {
            addCriterion("x00081250 >=", value, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250LessThan(Object value) {
            addCriterion("x00081250 <", value, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250LessThanOrEqualTo(Object value) {
            addCriterion("x00081250 <=", value, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250In(List<Object> values) {
            addCriterion("x00081250 in", values, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250NotIn(List<Object> values) {
            addCriterion("x00081250 not in", values, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250Between(Object value1, Object value2) {
            addCriterion("x00081250 between", value1, value2, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00081250NotBetween(Object value1, Object value2) {
            addCriterion("x00081250 not between", value1, value2, "x00081250");
            return (Criteria) this;
        }

        public Criteria andX00200011IsNull() {
            addCriterion("x00200011 is null");
            return (Criteria) this;
        }

        public Criteria andX00200011IsNotNull() {
            addCriterion("x00200011 is not null");
            return (Criteria) this;
        }

        public Criteria andX00200011EqualTo(String value) {
            addCriterion("x00200011 =", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011NotEqualTo(String value) {
            addCriterion("x00200011 <>", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011GreaterThan(String value) {
            addCriterion("x00200011 >", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011GreaterThanOrEqualTo(String value) {
            addCriterion("x00200011 >=", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011LessThan(String value) {
            addCriterion("x00200011 <", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011LessThanOrEqualTo(String value) {
            addCriterion("x00200011 <=", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011Like(String value) {
            addCriterion("x00200011 like", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011NotLike(String value) {
            addCriterion("x00200011 not like", value, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011In(List<String> values) {
            addCriterion("x00200011 in", values, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011NotIn(List<String> values) {
            addCriterion("x00200011 not in", values, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011Between(String value1, String value2) {
            addCriterion("x00200011 between", value1, value2, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00200011NotBetween(String value1, String value2) {
            addCriterion("x00200011 not between", value1, value2, "x00200011");
            return (Criteria) this;
        }

        public Criteria andX00400244IsNull() {
            addCriterion("x00400244 is null");
            return (Criteria) this;
        }

        public Criteria andX00400244IsNotNull() {
            addCriterion("x00400244 is not null");
            return (Criteria) this;
        }

        public Criteria andX00400244EqualTo(Date value) {
            addCriterionForJDBCDate("x00400244 =", value, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244NotEqualTo(Date value) {
            addCriterionForJDBCDate("x00400244 <>", value, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244GreaterThan(Date value) {
            addCriterionForJDBCDate("x00400244 >", value, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00400244 >=", value, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244LessThan(Date value) {
            addCriterionForJDBCDate("x00400244 <", value, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00400244 <=", value, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244In(List<Date> values) {
            addCriterionForJDBCDate("x00400244 in", values, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244NotIn(List<Date> values) {
            addCriterionForJDBCDate("x00400244 not in", values, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244Between(Date value1, Date value2) {
            addCriterionForJDBCDate("x00400244 between", value1, value2, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400244NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("x00400244 not between", value1, value2, "x00400244");
            return (Criteria) this;
        }

        public Criteria andX00400245IsNull() {
            addCriterion("x00400245 is null");
            return (Criteria) this;
        }

        public Criteria andX00400245IsNotNull() {
            addCriterion("x00400245 is not null");
            return (Criteria) this;
        }

        public Criteria andX00400245EqualTo(Short value) {
            addCriterion("x00400245 =", value, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245NotEqualTo(Short value) {
            addCriterion("x00400245 <>", value, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245GreaterThan(Short value) {
            addCriterion("x00400245 >", value, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245GreaterThanOrEqualTo(Short value) {
            addCriterion("x00400245 >=", value, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245LessThan(Short value) {
            addCriterion("x00400245 <", value, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245LessThanOrEqualTo(Short value) {
            addCriterion("x00400245 <=", value, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245In(List<Short> values) {
            addCriterion("x00400245 in", values, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245NotIn(List<Short> values) {
            addCriterion("x00400245 not in", values, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245Between(Short value1, Short value2) {
            addCriterion("x00400245 between", value1, value2, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00400245NotBetween(Short value1, Short value2) {
            addCriterion("x00400245 not between", value1, value2, "x00400245");
            return (Criteria) this;
        }

        public Criteria andX00080031IsNull() {
            addCriterion("x00080031 is null");
            return (Criteria) this;
        }

        public Criteria andX00080031IsNotNull() {
            addCriterion("x00080031 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080031EqualTo(Short value) {
            addCriterion("x00080031 =", value, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031NotEqualTo(Short value) {
            addCriterion("x00080031 <>", value, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031GreaterThan(Short value) {
            addCriterion("x00080031 >", value, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031GreaterThanOrEqualTo(Short value) {
            addCriterion("x00080031 >=", value, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031LessThan(Short value) {
            addCriterion("x00080031 <", value, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031LessThanOrEqualTo(Short value) {
            addCriterion("x00080031 <=", value, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031In(List<Short> values) {
            addCriterion("x00080031 in", values, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031NotIn(List<Short> values) {
            addCriterion("x00080031 not in", values, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031Between(Short value1, Short value2) {
            addCriterion("x00080031 between", value1, value2, "x00080031");
            return (Criteria) this;
        }

        public Criteria andX00080031NotBetween(Short value1, Short value2) {
            addCriterion("x00080031 not between", value1, value2, "x00080031");
            return (Criteria) this;
        }

        public Criteria andJsonIsNull() {
            addCriterion("json is null");
            return (Criteria) this;
        }

        public Criteria andJsonIsNotNull() {
            addCriterion("json is not null");
            return (Criteria) this;
        }

        public Criteria andJsonEqualTo(Object value) {
            addCriterion("json =", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotEqualTo(Object value) {
            addCriterion("json <>", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThan(Object value) {
            addCriterion("json >", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThanOrEqualTo(Object value) {
            addCriterion("json >=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThan(Object value) {
            addCriterion("json <", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThanOrEqualTo(Object value) {
            addCriterion("json <=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonIn(List<Object> values) {
            addCriterion("json in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotIn(List<Object> values) {
            addCriterion("json not in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonBetween(Object value1, Object value2) {
            addCriterion("json between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotBetween(Object value1, Object value2) {
            addCriterion("json not between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNull() {
            addCriterion("createdAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNotNull() {
            addCriterion("createdAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedatEqualTo(Date value) {
            addCriterion("createdAt =", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotEqualTo(Date value) {
            addCriterion("createdAt <>", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThan(Date value) {
            addCriterion("createdAt >", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("createdAt >=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThan(Date value) {
            addCriterion("createdAt <", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThanOrEqualTo(Date value) {
            addCriterion("createdAt <=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatIn(List<Date> values) {
            addCriterion("createdAt in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotIn(List<Date> values) {
            addCriterion("createdAt not in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatBetween(Date value1, Date value2) {
            addCriterion("createdAt between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotBetween(Date value1, Date value2) {
            addCriterion("createdAt not between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNull() {
            addCriterion("updatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNotNull() {
            addCriterion("updatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatEqualTo(Date value) {
            addCriterion("updatedAt =", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotEqualTo(Date value) {
            addCriterion("updatedAt <>", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThan(Date value) {
            addCriterion("updatedAt >", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedAt >=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThan(Date value) {
            addCriterion("updatedAt <", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThanOrEqualTo(Date value) {
            addCriterion("updatedAt <=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIn(List<Date> values) {
            addCriterion("updatedAt in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotIn(List<Date> values) {
            addCriterion("updatedAt not in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatBetween(Date value1, Date value2) {
            addCriterion("updatedAt between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotBetween(Date value1, Date value2) {
            addCriterion("updatedAt not between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIsNull() {
            addCriterion("deleteStatus is null");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIsNotNull() {
            addCriterion("deleteStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeletestatusEqualTo(Integer value) {
            addCriterion("deleteStatus =", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotEqualTo(Integer value) {
            addCriterion("deleteStatus <>", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusGreaterThan(Integer value) {
            addCriterion("deleteStatus >", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteStatus >=", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusLessThan(Integer value) {
            addCriterion("deleteStatus <", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusLessThanOrEqualTo(Integer value) {
            addCriterion("deleteStatus <=", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIn(List<Integer> values) {
            addCriterion("deleteStatus in", values, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotIn(List<Integer> values) {
            addCriterion("deleteStatus not in", values, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusBetween(Integer value1, Integer value2) {
            addCriterion("deleteStatus between", value1, value2, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteStatus not between", value1, value2, "deletestatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Series
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Series
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}