package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Seriesrequestattributes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x0020000E
     *
     * @mbg.generated
     */
    private String x0020000e;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x00080050
     *
     * @mbg.generated
     */
    private String x00080050;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x00080051_x00400031
     *
     * @mbg.generated
     */
    private String x00080051X00400031;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x00080051_x00400032
     *
     * @mbg.generated
     */
    private String x00080051X00400032;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x00080051_x00400033
     *
     * @mbg.generated
     */
    private String x00080051X00400033;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x00321033
     *
     * @mbg.generated
     */
    private String x00321033;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x00401001
     *
     * @mbg.generated
     */
    private String x00401001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.x0020000D
     *
     * @mbg.generated
     */
    private String x0020000d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.SeriesRequestAttributes.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.id
     *
     * @return the value of public.SeriesRequestAttributes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.id
     *
     * @param id the value for public.SeriesRequestAttributes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x0020000E
     *
     * @return the value of public.SeriesRequestAttributes.x0020000E
     *
     * @mbg.generated
     */
    public String getX0020000e() {
        return x0020000e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x0020000E
     *
     * @param x0020000e the value for public.SeriesRequestAttributes.x0020000E
     *
     * @mbg.generated
     */
    public void setX0020000e(String x0020000e) {
        this.x0020000e = x0020000e == null ? null : x0020000e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x00080050
     *
     * @return the value of public.SeriesRequestAttributes.x00080050
     *
     * @mbg.generated
     */
    public String getX00080050() {
        return x00080050;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x00080050
     *
     * @param x00080050 the value for public.SeriesRequestAttributes.x00080050
     *
     * @mbg.generated
     */
    public void setX00080050(String x00080050) {
        this.x00080050 = x00080050 == null ? null : x00080050.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x00080051_x00400031
     *
     * @return the value of public.SeriesRequestAttributes.x00080051_x00400031
     *
     * @mbg.generated
     */
    public String getX00080051X00400031() {
        return x00080051X00400031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x00080051_x00400031
     *
     * @param x00080051X00400031 the value for public.SeriesRequestAttributes.x00080051_x00400031
     *
     * @mbg.generated
     */
    public void setX00080051X00400031(String x00080051X00400031) {
        this.x00080051X00400031 = x00080051X00400031 == null ? null : x00080051X00400031.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x00080051_x00400032
     *
     * @return the value of public.SeriesRequestAttributes.x00080051_x00400032
     *
     * @mbg.generated
     */
    public String getX00080051X00400032() {
        return x00080051X00400032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x00080051_x00400032
     *
     * @param x00080051X00400032 the value for public.SeriesRequestAttributes.x00080051_x00400032
     *
     * @mbg.generated
     */
    public void setX00080051X00400032(String x00080051X00400032) {
        this.x00080051X00400032 = x00080051X00400032 == null ? null : x00080051X00400032.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x00080051_x00400033
     *
     * @return the value of public.SeriesRequestAttributes.x00080051_x00400033
     *
     * @mbg.generated
     */
    public String getX00080051X00400033() {
        return x00080051X00400033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x00080051_x00400033
     *
     * @param x00080051X00400033 the value for public.SeriesRequestAttributes.x00080051_x00400033
     *
     * @mbg.generated
     */
    public void setX00080051X00400033(String x00080051X00400033) {
        this.x00080051X00400033 = x00080051X00400033 == null ? null : x00080051X00400033.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x00321033
     *
     * @return the value of public.SeriesRequestAttributes.x00321033
     *
     * @mbg.generated
     */
    public String getX00321033() {
        return x00321033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x00321033
     *
     * @param x00321033 the value for public.SeriesRequestAttributes.x00321033
     *
     * @mbg.generated
     */
    public void setX00321033(String x00321033) {
        this.x00321033 = x00321033 == null ? null : x00321033.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x00401001
     *
     * @return the value of public.SeriesRequestAttributes.x00401001
     *
     * @mbg.generated
     */
    public String getX00401001() {
        return x00401001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x00401001
     *
     * @param x00401001 the value for public.SeriesRequestAttributes.x00401001
     *
     * @mbg.generated
     */
    public void setX00401001(String x00401001) {
        this.x00401001 = x00401001 == null ? null : x00401001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.x0020000D
     *
     * @return the value of public.SeriesRequestAttributes.x0020000D
     *
     * @mbg.generated
     */
    public String getX0020000d() {
        return x0020000d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.x0020000D
     *
     * @param x0020000d the value for public.SeriesRequestAttributes.x0020000D
     *
     * @mbg.generated
     */
    public void setX0020000d(String x0020000d) {
        this.x0020000d = x0020000d == null ? null : x0020000d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.createdAt
     *
     * @return the value of public.SeriesRequestAttributes.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.createdAt
     *
     * @param createdat the value for public.SeriesRequestAttributes.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.SeriesRequestAttributes.updatedAt
     *
     * @return the value of public.SeriesRequestAttributes.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.SeriesRequestAttributes.updatedAt
     *
     * @param updatedat the value for public.SeriesRequestAttributes.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}