package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Series {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x0020000E
     *
     * @mbg.generated
     */
    private String x0020000e;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.seriesPath
     *
     * @mbg.generated
     */
    private String seriespath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x0020000D
     *
     * @mbg.generated
     */
    private String x0020000d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00080021
     *
     * @mbg.generated
     */
    private Date x00080021;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00080060
     *
     * @mbg.generated
     */
    private String x00080060;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x0008103E
     *
     * @mbg.generated
     */
    private String x0008103e;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x0008103F
     *
     * @mbg.generated
     */
    private Object x0008103f;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00081052
     *
     * @mbg.generated
     */
    private Object x00081052;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00081072
     *
     * @mbg.generated
     */
    private Object x00081072;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00081250
     *
     * @mbg.generated
     */
    private Object x00081250;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00200011
     *
     * @mbg.generated
     */
    private String x00200011;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00400244
     *
     * @mbg.generated
     */
    private Date x00400244;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00400245
     *
     * @mbg.generated
     */
    private Short x00400245;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.x00080031
     *
     * @mbg.generated
     */
    private Short x00080031;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.json
     *
     * @mbg.generated
     */
    private Object json;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Series.deleteStatus
     *
     * @mbg.generated
     */
    private Integer deletestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x0020000E
     *
     * @return the value of public.Series.x0020000E
     *
     * @mbg.generated
     */
    public String getX0020000e() {
        return x0020000e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x0020000E
     *
     * @param x0020000e the value for public.Series.x0020000E
     *
     * @mbg.generated
     */
    public void setX0020000e(String x0020000e) {
        this.x0020000e = x0020000e == null ? null : x0020000e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.seriesPath
     *
     * @return the value of public.Series.seriesPath
     *
     * @mbg.generated
     */
    public String getSeriespath() {
        return seriespath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.seriesPath
     *
     * @param seriespath the value for public.Series.seriesPath
     *
     * @mbg.generated
     */
    public void setSeriespath(String seriespath) {
        this.seriespath = seriespath == null ? null : seriespath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x0020000D
     *
     * @return the value of public.Series.x0020000D
     *
     * @mbg.generated
     */
    public String getX0020000d() {
        return x0020000d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x0020000D
     *
     * @param x0020000d the value for public.Series.x0020000D
     *
     * @mbg.generated
     */
    public void setX0020000d(String x0020000d) {
        this.x0020000d = x0020000d == null ? null : x0020000d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00080021
     *
     * @return the value of public.Series.x00080021
     *
     * @mbg.generated
     */
    public Date getX00080021() {
        return x00080021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00080021
     *
     * @param x00080021 the value for public.Series.x00080021
     *
     * @mbg.generated
     */
    public void setX00080021(Date x00080021) {
        this.x00080021 = x00080021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00080060
     *
     * @return the value of public.Series.x00080060
     *
     * @mbg.generated
     */
    public String getX00080060() {
        return x00080060;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00080060
     *
     * @param x00080060 the value for public.Series.x00080060
     *
     * @mbg.generated
     */
    public void setX00080060(String x00080060) {
        this.x00080060 = x00080060 == null ? null : x00080060.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x0008103E
     *
     * @return the value of public.Series.x0008103E
     *
     * @mbg.generated
     */
    public String getX0008103e() {
        return x0008103e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x0008103E
     *
     * @param x0008103e the value for public.Series.x0008103E
     *
     * @mbg.generated
     */
    public void setX0008103e(String x0008103e) {
        this.x0008103e = x0008103e == null ? null : x0008103e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x0008103F
     *
     * @return the value of public.Series.x0008103F
     *
     * @mbg.generated
     */
    public Object getX0008103f() {
        return x0008103f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x0008103F
     *
     * @param x0008103f the value for public.Series.x0008103F
     *
     * @mbg.generated
     */
    public void setX0008103f(Object x0008103f) {
        this.x0008103f = x0008103f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00081052
     *
     * @return the value of public.Series.x00081052
     *
     * @mbg.generated
     */
    public Object getX00081052() {
        return x00081052;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00081052
     *
     * @param x00081052 the value for public.Series.x00081052
     *
     * @mbg.generated
     */
    public void setX00081052(Object x00081052) {
        this.x00081052 = x00081052;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00081072
     *
     * @return the value of public.Series.x00081072
     *
     * @mbg.generated
     */
    public Object getX00081072() {
        return x00081072;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00081072
     *
     * @param x00081072 the value for public.Series.x00081072
     *
     * @mbg.generated
     */
    public void setX00081072(Object x00081072) {
        this.x00081072 = x00081072;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00081250
     *
     * @return the value of public.Series.x00081250
     *
     * @mbg.generated
     */
    public Object getX00081250() {
        return x00081250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00081250
     *
     * @param x00081250 the value for public.Series.x00081250
     *
     * @mbg.generated
     */
    public void setX00081250(Object x00081250) {
        this.x00081250 = x00081250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00200011
     *
     * @return the value of public.Series.x00200011
     *
     * @mbg.generated
     */
    public String getX00200011() {
        return x00200011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00200011
     *
     * @param x00200011 the value for public.Series.x00200011
     *
     * @mbg.generated
     */
    public void setX00200011(String x00200011) {
        this.x00200011 = x00200011 == null ? null : x00200011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00400244
     *
     * @return the value of public.Series.x00400244
     *
     * @mbg.generated
     */
    public Date getX00400244() {
        return x00400244;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00400244
     *
     * @param x00400244 the value for public.Series.x00400244
     *
     * @mbg.generated
     */
    public void setX00400244(Date x00400244) {
        this.x00400244 = x00400244;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00400245
     *
     * @return the value of public.Series.x00400245
     *
     * @mbg.generated
     */
    public Short getX00400245() {
        return x00400245;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00400245
     *
     * @param x00400245 the value for public.Series.x00400245
     *
     * @mbg.generated
     */
    public void setX00400245(Short x00400245) {
        this.x00400245 = x00400245;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.x00080031
     *
     * @return the value of public.Series.x00080031
     *
     * @mbg.generated
     */
    public Short getX00080031() {
        return x00080031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.x00080031
     *
     * @param x00080031 the value for public.Series.x00080031
     *
     * @mbg.generated
     */
    public void setX00080031(Short x00080031) {
        this.x00080031 = x00080031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.json
     *
     * @return the value of public.Series.json
     *
     * @mbg.generated
     */
    public Object getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.json
     *
     * @param json the value for public.Series.json
     *
     * @mbg.generated
     */
    public void setJson(Object json) {
        this.json = json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.createdAt
     *
     * @return the value of public.Series.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.createdAt
     *
     * @param createdat the value for public.Series.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.updatedAt
     *
     * @return the value of public.Series.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.updatedAt
     *
     * @param updatedat the value for public.Series.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Series.deleteStatus
     *
     * @return the value of public.Series.deleteStatus
     *
     * @mbg.generated
     */
    public Integer getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Series.deleteStatus
     *
     * @param deletestatus the value for public.Series.deleteStatus
     *
     * @mbg.generated
     */
    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }
}