package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Sessions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Sessions.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Sessions.expires
     *
     * @mbg.generated
     */
    private Date expires;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Sessions.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Sessions.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Sessions.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Sessions.sid
     *
     * @return the value of public.Sessions.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Sessions.sid
     *
     * @param sid the value for public.Sessions.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Sessions.expires
     *
     * @return the value of public.Sessions.expires
     *
     * @mbg.generated
     */
    public Date getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Sessions.expires
     *
     * @param expires the value for public.Sessions.expires
     *
     * @mbg.generated
     */
    public void setExpires(Date expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Sessions.data
     *
     * @return the value of public.Sessions.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Sessions.data
     *
     * @param data the value for public.Sessions.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Sessions.createdAt
     *
     * @return the value of public.Sessions.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Sessions.createdAt
     *
     * @param createdat the value for public.Sessions.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Sessions.updatedAt
     *
     * @return the value of public.Sessions.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Sessions.updatedAt
     *
     * @param updatedat the value for public.Sessions.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}