package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StudyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public StudyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andX0020000dIsNull() {
            addCriterion("x0020000D is null");
            return (Criteria) this;
        }

        public Criteria andX0020000dIsNotNull() {
            addCriterion("x0020000D is not null");
            return (Criteria) this;
        }

        public Criteria andX0020000dEqualTo(String value) {
            addCriterion("x0020000D =", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotEqualTo(String value) {
            addCriterion("x0020000D <>", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dGreaterThan(String value) {
            addCriterion("x0020000D >", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dGreaterThanOrEqualTo(String value) {
            addCriterion("x0020000D >=", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLessThan(String value) {
            addCriterion("x0020000D <", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLessThanOrEqualTo(String value) {
            addCriterion("x0020000D <=", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dLike(String value) {
            addCriterion("x0020000D like", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotLike(String value) {
            addCriterion("x0020000D not like", value, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dIn(List<String> values) {
            addCriterion("x0020000D in", values, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotIn(List<String> values) {
            addCriterion("x0020000D not in", values, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dBetween(String value1, String value2) {
            addCriterion("x0020000D between", value1, value2, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andX0020000dNotBetween(String value1, String value2) {
            addCriterion("x0020000D not between", value1, value2, "x0020000d");
            return (Criteria) this;
        }

        public Criteria andStudypathIsNull() {
            addCriterion("studyPath is null");
            return (Criteria) this;
        }

        public Criteria andStudypathIsNotNull() {
            addCriterion("studyPath is not null");
            return (Criteria) this;
        }

        public Criteria andStudypathEqualTo(String value) {
            addCriterion("studyPath =", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathNotEqualTo(String value) {
            addCriterion("studyPath <>", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathGreaterThan(String value) {
            addCriterion("studyPath >", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathGreaterThanOrEqualTo(String value) {
            addCriterion("studyPath >=", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathLessThan(String value) {
            addCriterion("studyPath <", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathLessThanOrEqualTo(String value) {
            addCriterion("studyPath <=", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathLike(String value) {
            addCriterion("studyPath like", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathNotLike(String value) {
            addCriterion("studyPath not like", value, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathIn(List<String> values) {
            addCriterion("studyPath in", values, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathNotIn(List<String> values) {
            addCriterion("studyPath not in", values, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathBetween(String value1, String value2) {
            addCriterion("studyPath between", value1, value2, "studypath");
            return (Criteria) this;
        }

        public Criteria andStudypathNotBetween(String value1, String value2) {
            addCriterion("studyPath not between", value1, value2, "studypath");
            return (Criteria) this;
        }

        public Criteria andX00100020IsNull() {
            addCriterion("x00100020 is null");
            return (Criteria) this;
        }

        public Criteria andX00100020IsNotNull() {
            addCriterion("x00100020 is not null");
            return (Criteria) this;
        }

        public Criteria andX00100020EqualTo(String value) {
            addCriterion("x00100020 =", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotEqualTo(String value) {
            addCriterion("x00100020 <>", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020GreaterThan(String value) {
            addCriterion("x00100020 >", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020GreaterThanOrEqualTo(String value) {
            addCriterion("x00100020 >=", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020LessThan(String value) {
            addCriterion("x00100020 <", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020LessThanOrEqualTo(String value) {
            addCriterion("x00100020 <=", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020Like(String value) {
            addCriterion("x00100020 like", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotLike(String value) {
            addCriterion("x00100020 not like", value, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020In(List<String> values) {
            addCriterion("x00100020 in", values, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotIn(List<String> values) {
            addCriterion("x00100020 not in", values, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020Between(String value1, String value2) {
            addCriterion("x00100020 between", value1, value2, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00100020NotBetween(String value1, String value2) {
            addCriterion("x00100020 not between", value1, value2, "x00100020");
            return (Criteria) this;
        }

        public Criteria andX00080005IsNull() {
            addCriterion("x00080005 is null");
            return (Criteria) this;
        }

        public Criteria andX00080005IsNotNull() {
            addCriterion("x00080005 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080005EqualTo(Object value) {
            addCriterion("x00080005 =", value, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005NotEqualTo(Object value) {
            addCriterion("x00080005 <>", value, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005GreaterThan(Object value) {
            addCriterion("x00080005 >", value, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005GreaterThanOrEqualTo(Object value) {
            addCriterion("x00080005 >=", value, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005LessThan(Object value) {
            addCriterion("x00080005 <", value, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005LessThanOrEqualTo(Object value) {
            addCriterion("x00080005 <=", value, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005In(List<Object> values) {
            addCriterion("x00080005 in", values, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005NotIn(List<Object> values) {
            addCriterion("x00080005 not in", values, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005Between(Object value1, Object value2) {
            addCriterion("x00080005 between", value1, value2, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080005NotBetween(Object value1, Object value2) {
            addCriterion("x00080005 not between", value1, value2, "x00080005");
            return (Criteria) this;
        }

        public Criteria andX00080020IsNull() {
            addCriterion("x00080020 is null");
            return (Criteria) this;
        }

        public Criteria andX00080020IsNotNull() {
            addCriterion("x00080020 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080020EqualTo(Date value) {
            addCriterionForJDBCDate("x00080020 =", value, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020NotEqualTo(Date value) {
            addCriterionForJDBCDate("x00080020 <>", value, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020GreaterThan(Date value) {
            addCriterionForJDBCDate("x00080020 >", value, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00080020 >=", value, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020LessThan(Date value) {
            addCriterionForJDBCDate("x00080020 <", value, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("x00080020 <=", value, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020In(List<Date> values) {
            addCriterionForJDBCDate("x00080020 in", values, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020NotIn(List<Date> values) {
            addCriterionForJDBCDate("x00080020 not in", values, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020Between(Date value1, Date value2) {
            addCriterionForJDBCDate("x00080020 between", value1, value2, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080020NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("x00080020 not between", value1, value2, "x00080020");
            return (Criteria) this;
        }

        public Criteria andX00080030IsNull() {
            addCriterion("x00080030 is null");
            return (Criteria) this;
        }

        public Criteria andX00080030IsNotNull() {
            addCriterion("x00080030 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080030EqualTo(Short value) {
            addCriterion("x00080030 =", value, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030NotEqualTo(Short value) {
            addCriterion("x00080030 <>", value, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030GreaterThan(Short value) {
            addCriterion("x00080030 >", value, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030GreaterThanOrEqualTo(Short value) {
            addCriterion("x00080030 >=", value, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030LessThan(Short value) {
            addCriterion("x00080030 <", value, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030LessThanOrEqualTo(Short value) {
            addCriterion("x00080030 <=", value, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030In(List<Short> values) {
            addCriterion("x00080030 in", values, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030NotIn(List<Short> values) {
            addCriterion("x00080030 not in", values, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030Between(Short value1, Short value2) {
            addCriterion("x00080030 between", value1, value2, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080030NotBetween(Short value1, Short value2) {
            addCriterion("x00080030 not between", value1, value2, "x00080030");
            return (Criteria) this;
        }

        public Criteria andX00080050IsNull() {
            addCriterion("x00080050 is null");
            return (Criteria) this;
        }

        public Criteria andX00080050IsNotNull() {
            addCriterion("x00080050 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080050EqualTo(String value) {
            addCriterion("x00080050 =", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050NotEqualTo(String value) {
            addCriterion("x00080050 <>", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050GreaterThan(String value) {
            addCriterion("x00080050 >", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050GreaterThanOrEqualTo(String value) {
            addCriterion("x00080050 >=", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050LessThan(String value) {
            addCriterion("x00080050 <", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050LessThanOrEqualTo(String value) {
            addCriterion("x00080050 <=", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050Like(String value) {
            addCriterion("x00080050 like", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050NotLike(String value) {
            addCriterion("x00080050 not like", value, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050In(List<String> values) {
            addCriterion("x00080050 in", values, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050NotIn(List<String> values) {
            addCriterion("x00080050 not in", values, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050Between(String value1, String value2) {
            addCriterion("x00080050 between", value1, value2, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080050NotBetween(String value1, String value2) {
            addCriterion("x00080050 not between", value1, value2, "x00080050");
            return (Criteria) this;
        }

        public Criteria andX00080056IsNull() {
            addCriterion("x00080056 is null");
            return (Criteria) this;
        }

        public Criteria andX00080056IsNotNull() {
            addCriterion("x00080056 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080056EqualTo(String value) {
            addCriterion("x00080056 =", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056NotEqualTo(String value) {
            addCriterion("x00080056 <>", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056GreaterThan(String value) {
            addCriterion("x00080056 >", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056GreaterThanOrEqualTo(String value) {
            addCriterion("x00080056 >=", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056LessThan(String value) {
            addCriterion("x00080056 <", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056LessThanOrEqualTo(String value) {
            addCriterion("x00080056 <=", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056Like(String value) {
            addCriterion("x00080056 like", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056NotLike(String value) {
            addCriterion("x00080056 not like", value, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056In(List<String> values) {
            addCriterion("x00080056 in", values, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056NotIn(List<String> values) {
            addCriterion("x00080056 not in", values, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056Between(String value1, String value2) {
            addCriterion("x00080056 between", value1, value2, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080056NotBetween(String value1, String value2) {
            addCriterion("x00080056 not between", value1, value2, "x00080056");
            return (Criteria) this;
        }

        public Criteria andX00080090IsNull() {
            addCriterion("x00080090 is null");
            return (Criteria) this;
        }

        public Criteria andX00080090IsNotNull() {
            addCriterion("x00080090 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080090EqualTo(Integer value) {
            addCriterion("x00080090 =", value, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090NotEqualTo(Integer value) {
            addCriterion("x00080090 <>", value, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090GreaterThan(Integer value) {
            addCriterion("x00080090 >", value, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090GreaterThanOrEqualTo(Integer value) {
            addCriterion("x00080090 >=", value, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090LessThan(Integer value) {
            addCriterion("x00080090 <", value, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090LessThanOrEqualTo(Integer value) {
            addCriterion("x00080090 <=", value, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090In(List<Integer> values) {
            addCriterion("x00080090 in", values, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090NotIn(List<Integer> values) {
            addCriterion("x00080090 not in", values, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090Between(Integer value1, Integer value2) {
            addCriterion("x00080090 between", value1, value2, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080090NotBetween(Integer value1, Integer value2) {
            addCriterion("x00080090 not between", value1, value2, "x00080090");
            return (Criteria) this;
        }

        public Criteria andX00080201IsNull() {
            addCriterion("x00080201 is null");
            return (Criteria) this;
        }

        public Criteria andX00080201IsNotNull() {
            addCriterion("x00080201 is not null");
            return (Criteria) this;
        }

        public Criteria andX00080201EqualTo(String value) {
            addCriterion("x00080201 =", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201NotEqualTo(String value) {
            addCriterion("x00080201 <>", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201GreaterThan(String value) {
            addCriterion("x00080201 >", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201GreaterThanOrEqualTo(String value) {
            addCriterion("x00080201 >=", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201LessThan(String value) {
            addCriterion("x00080201 <", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201LessThanOrEqualTo(String value) {
            addCriterion("x00080201 <=", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201Like(String value) {
            addCriterion("x00080201 like", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201NotLike(String value) {
            addCriterion("x00080201 not like", value, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201In(List<String> values) {
            addCriterion("x00080201 in", values, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201NotIn(List<String> values) {
            addCriterion("x00080201 not in", values, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201Between(String value1, String value2) {
            addCriterion("x00080201 between", value1, value2, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00080201NotBetween(String value1, String value2) {
            addCriterion("x00080201 not between", value1, value2, "x00080201");
            return (Criteria) this;
        }

        public Criteria andX00200010IsNull() {
            addCriterion("x00200010 is null");
            return (Criteria) this;
        }

        public Criteria andX00200010IsNotNull() {
            addCriterion("x00200010 is not null");
            return (Criteria) this;
        }

        public Criteria andX00200010EqualTo(String value) {
            addCriterion("x00200010 =", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010NotEqualTo(String value) {
            addCriterion("x00200010 <>", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010GreaterThan(String value) {
            addCriterion("x00200010 >", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010GreaterThanOrEqualTo(String value) {
            addCriterion("x00200010 >=", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010LessThan(String value) {
            addCriterion("x00200010 <", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010LessThanOrEqualTo(String value) {
            addCriterion("x00200010 <=", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010Like(String value) {
            addCriterion("x00200010 like", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010NotLike(String value) {
            addCriterion("x00200010 not like", value, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010In(List<String> values) {
            addCriterion("x00200010 in", values, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010NotIn(List<String> values) {
            addCriterion("x00200010 not in", values, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010Between(String value1, String value2) {
            addCriterion("x00200010 between", value1, value2, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00200010NotBetween(String value1, String value2) {
            addCriterion("x00200010 not between", value1, value2, "x00200010");
            return (Criteria) this;
        }

        public Criteria andX00201206IsNull() {
            addCriterion("x00201206 is null");
            return (Criteria) this;
        }

        public Criteria andX00201206IsNotNull() {
            addCriterion("x00201206 is not null");
            return (Criteria) this;
        }

        public Criteria andX00201206EqualTo(String value) {
            addCriterion("x00201206 =", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206NotEqualTo(String value) {
            addCriterion("x00201206 <>", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206GreaterThan(String value) {
            addCriterion("x00201206 >", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206GreaterThanOrEqualTo(String value) {
            addCriterion("x00201206 >=", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206LessThan(String value) {
            addCriterion("x00201206 <", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206LessThanOrEqualTo(String value) {
            addCriterion("x00201206 <=", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206Like(String value) {
            addCriterion("x00201206 like", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206NotLike(String value) {
            addCriterion("x00201206 not like", value, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206In(List<String> values) {
            addCriterion("x00201206 in", values, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206NotIn(List<String> values) {
            addCriterion("x00201206 not in", values, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206Between(String value1, String value2) {
            addCriterion("x00201206 between", value1, value2, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201206NotBetween(String value1, String value2) {
            addCriterion("x00201206 not between", value1, value2, "x00201206");
            return (Criteria) this;
        }

        public Criteria andX00201208IsNull() {
            addCriterion("x00201208 is null");
            return (Criteria) this;
        }

        public Criteria andX00201208IsNotNull() {
            addCriterion("x00201208 is not null");
            return (Criteria) this;
        }

        public Criteria andX00201208EqualTo(String value) {
            addCriterion("x00201208 =", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208NotEqualTo(String value) {
            addCriterion("x00201208 <>", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208GreaterThan(String value) {
            addCriterion("x00201208 >", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208GreaterThanOrEqualTo(String value) {
            addCriterion("x00201208 >=", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208LessThan(String value) {
            addCriterion("x00201208 <", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208LessThanOrEqualTo(String value) {
            addCriterion("x00201208 <=", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208Like(String value) {
            addCriterion("x00201208 like", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208NotLike(String value) {
            addCriterion("x00201208 not like", value, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208In(List<String> values) {
            addCriterion("x00201208 in", values, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208NotIn(List<String> values) {
            addCriterion("x00201208 not in", values, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208Between(String value1, String value2) {
            addCriterion("x00201208 between", value1, value2, "x00201208");
            return (Criteria) this;
        }

        public Criteria andX00201208NotBetween(String value1, String value2) {
            addCriterion("x00201208 not between", value1, value2, "x00201208");
            return (Criteria) this;
        }

        public Criteria andJsonIsNull() {
            addCriterion("json is null");
            return (Criteria) this;
        }

        public Criteria andJsonIsNotNull() {
            addCriterion("json is not null");
            return (Criteria) this;
        }

        public Criteria andJsonEqualTo(Object value) {
            addCriterion("json =", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotEqualTo(Object value) {
            addCriterion("json <>", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThan(Object value) {
            addCriterion("json >", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonGreaterThanOrEqualTo(Object value) {
            addCriterion("json >=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThan(Object value) {
            addCriterion("json <", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonLessThanOrEqualTo(Object value) {
            addCriterion("json <=", value, "json");
            return (Criteria) this;
        }

        public Criteria andJsonIn(List<Object> values) {
            addCriterion("json in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotIn(List<Object> values) {
            addCriterion("json not in", values, "json");
            return (Criteria) this;
        }

        public Criteria andJsonBetween(Object value1, Object value2) {
            addCriterion("json between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andJsonNotBetween(Object value1, Object value2) {
            addCriterion("json not between", value1, value2, "json");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNull() {
            addCriterion("createdAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNotNull() {
            addCriterion("createdAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedatEqualTo(Date value) {
            addCriterion("createdAt =", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotEqualTo(Date value) {
            addCriterion("createdAt <>", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThan(Date value) {
            addCriterion("createdAt >", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("createdAt >=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThan(Date value) {
            addCriterion("createdAt <", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThanOrEqualTo(Date value) {
            addCriterion("createdAt <=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatIn(List<Date> values) {
            addCriterion("createdAt in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotIn(List<Date> values) {
            addCriterion("createdAt not in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatBetween(Date value1, Date value2) {
            addCriterion("createdAt between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotBetween(Date value1, Date value2) {
            addCriterion("createdAt not between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNull() {
            addCriterion("updatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNotNull() {
            addCriterion("updatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatEqualTo(Date value) {
            addCriterion("updatedAt =", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotEqualTo(Date value) {
            addCriterion("updatedAt <>", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThan(Date value) {
            addCriterion("updatedAt >", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedAt >=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThan(Date value) {
            addCriterion("updatedAt <", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThanOrEqualTo(Date value) {
            addCriterion("updatedAt <=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIn(List<Date> values) {
            addCriterion("updatedAt in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotIn(List<Date> values) {
            addCriterion("updatedAt not in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatBetween(Date value1, Date value2) {
            addCriterion("updatedAt between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotBetween(Date value1, Date value2) {
            addCriterion("updatedAt not between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIsNull() {
            addCriterion("deleteStatus is null");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIsNotNull() {
            addCriterion("deleteStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeletestatusEqualTo(Integer value) {
            addCriterion("deleteStatus =", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotEqualTo(Integer value) {
            addCriterion("deleteStatus <>", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusGreaterThan(Integer value) {
            addCriterion("deleteStatus >", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteStatus >=", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusLessThan(Integer value) {
            addCriterion("deleteStatus <", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusLessThanOrEqualTo(Integer value) {
            addCriterion("deleteStatus <=", value, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusIn(List<Integer> values) {
            addCriterion("deleteStatus in", values, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotIn(List<Integer> values) {
            addCriterion("deleteStatus not in", values, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusBetween(Integer value1, Integer value2) {
            addCriterion("deleteStatus between", value1, value2, "deletestatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteStatus not between", value1, value2, "deletestatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Study
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}