package org.dcm4che3.tool.dcmqrscp.mybatis.entity;

import java.util.Date;

public class Study {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x0020000D
     *
     * @mbg.generated
     */
    private String x0020000d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.studyPath
     *
     * @mbg.generated
     */
    private String studypath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00100020
     *
     * @mbg.generated
     */
    private String x00100020;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080005
     *
     * @mbg.generated
     */
    private Object x00080005;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080020
     *
     * @mbg.generated
     */
    private Date x00080020;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080030
     *
     * @mbg.generated
     */
    private Short x00080030;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080050
     *
     * @mbg.generated
     */
    private String x00080050;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080056
     *
     * @mbg.generated
     */
    private String x00080056;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080090
     *
     * @mbg.generated
     */
    private Integer x00080090;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00080201
     *
     * @mbg.generated
     */
    private String x00080201;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00200010
     *
     * @mbg.generated
     */
    private String x00200010;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00201206
     *
     * @mbg.generated
     */
    private String x00201206;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.x00201208
     *
     * @mbg.generated
     */
    private String x00201208;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.json
     *
     * @mbg.generated
     */
    private Object json;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.createdAt
     *
     * @mbg.generated
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.updatedAt
     *
     * @mbg.generated
     */
    private Date updatedat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Study.deleteStatus
     *
     * @mbg.generated
     */
    private Integer deletestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x0020000D
     *
     * @return the value of public.Study.x0020000D
     *
     * @mbg.generated
     */
    public String getX0020000d() {
        return x0020000d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x0020000D
     *
     * @param x0020000d the value for public.Study.x0020000D
     *
     * @mbg.generated
     */
    public void setX0020000d(String x0020000d) {
        this.x0020000d = x0020000d == null ? null : x0020000d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.studyPath
     *
     * @return the value of public.Study.studyPath
     *
     * @mbg.generated
     */
    public String getStudypath() {
        return studypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.studyPath
     *
     * @param studypath the value for public.Study.studyPath
     *
     * @mbg.generated
     */
    public void setStudypath(String studypath) {
        this.studypath = studypath == null ? null : studypath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00100020
     *
     * @return the value of public.Study.x00100020
     *
     * @mbg.generated
     */
    public String getX00100020() {
        return x00100020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00100020
     *
     * @param x00100020 the value for public.Study.x00100020
     *
     * @mbg.generated
     */
    public void setX00100020(String x00100020) {
        this.x00100020 = x00100020 == null ? null : x00100020.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080005
     *
     * @return the value of public.Study.x00080005
     *
     * @mbg.generated
     */
    public Object getX00080005() {
        return x00080005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080005
     *
     * @param x00080005 the value for public.Study.x00080005
     *
     * @mbg.generated
     */
    public void setX00080005(Object x00080005) {
        this.x00080005 = x00080005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080020
     *
     * @return the value of public.Study.x00080020
     *
     * @mbg.generated
     */
    public Date getX00080020() {
        return x00080020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080020
     *
     * @param x00080020 the value for public.Study.x00080020
     *
     * @mbg.generated
     */
    public void setX00080020(Date x00080020) {
        this.x00080020 = x00080020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080030
     *
     * @return the value of public.Study.x00080030
     *
     * @mbg.generated
     */
    public Short getX00080030() {
        return x00080030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080030
     *
     * @param x00080030 the value for public.Study.x00080030
     *
     * @mbg.generated
     */
    public void setX00080030(Short x00080030) {
        this.x00080030 = x00080030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080050
     *
     * @return the value of public.Study.x00080050
     *
     * @mbg.generated
     */
    public String getX00080050() {
        return x00080050;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080050
     *
     * @param x00080050 the value for public.Study.x00080050
     *
     * @mbg.generated
     */
    public void setX00080050(String x00080050) {
        this.x00080050 = x00080050 == null ? null : x00080050.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080056
     *
     * @return the value of public.Study.x00080056
     *
     * @mbg.generated
     */
    public String getX00080056() {
        return x00080056;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080056
     *
     * @param x00080056 the value for public.Study.x00080056
     *
     * @mbg.generated
     */
    public void setX00080056(String x00080056) {
        this.x00080056 = x00080056 == null ? null : x00080056.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080090
     *
     * @return the value of public.Study.x00080090
     *
     * @mbg.generated
     */
    public Integer getX00080090() {
        return x00080090;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080090
     *
     * @param x00080090 the value for public.Study.x00080090
     *
     * @mbg.generated
     */
    public void setX00080090(Integer x00080090) {
        this.x00080090 = x00080090;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00080201
     *
     * @return the value of public.Study.x00080201
     *
     * @mbg.generated
     */
    public String getX00080201() {
        return x00080201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00080201
     *
     * @param x00080201 the value for public.Study.x00080201
     *
     * @mbg.generated
     */
    public void setX00080201(String x00080201) {
        this.x00080201 = x00080201 == null ? null : x00080201.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00200010
     *
     * @return the value of public.Study.x00200010
     *
     * @mbg.generated
     */
    public String getX00200010() {
        return x00200010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00200010
     *
     * @param x00200010 the value for public.Study.x00200010
     *
     * @mbg.generated
     */
    public void setX00200010(String x00200010) {
        this.x00200010 = x00200010 == null ? null : x00200010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00201206
     *
     * @return the value of public.Study.x00201206
     *
     * @mbg.generated
     */
    public String getX00201206() {
        return x00201206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00201206
     *
     * @param x00201206 the value for public.Study.x00201206
     *
     * @mbg.generated
     */
    public void setX00201206(String x00201206) {
        this.x00201206 = x00201206 == null ? null : x00201206.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.x00201208
     *
     * @return the value of public.Study.x00201208
     *
     * @mbg.generated
     */
    public String getX00201208() {
        return x00201208;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.x00201208
     *
     * @param x00201208 the value for public.Study.x00201208
     *
     * @mbg.generated
     */
    public void setX00201208(String x00201208) {
        this.x00201208 = x00201208 == null ? null : x00201208.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.json
     *
     * @return the value of public.Study.json
     *
     * @mbg.generated
     */
    public Object getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.json
     *
     * @param json the value for public.Study.json
     *
     * @mbg.generated
     */
    public void setJson(Object json) {
        this.json = json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.createdAt
     *
     * @return the value of public.Study.createdAt
     *
     * @mbg.generated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.createdAt
     *
     * @param createdat the value for public.Study.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.updatedAt
     *
     * @return the value of public.Study.updatedAt
     *
     * @mbg.generated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.updatedAt
     *
     * @param updatedat the value for public.Study.updatedAt
     *
     * @mbg.generated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Study.deleteStatus
     *
     * @return the value of public.Study.deleteStatus
     *
     * @mbg.generated
     */
    public Integer getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Study.deleteStatus
     *
     * @param deletestatus the value for public.Study.deleteStatus
     *
     * @mbg.generated
     */
    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }
}