package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Dicomtojpegtask;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.DicomtojpegtaskExample;

public interface DicomtojpegtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    long countByExample(DicomtojpegtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int deleteByExample(DicomtojpegtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int insert(Dicomtojpegtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int insertSelective(Dicomtojpegtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    List<Dicomtojpegtask> selectByExample(DicomtojpegtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    Dicomtojpegtask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dicomtojpegtask record, @Param("example") DicomtojpegtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dicomtojpegtask record, @Param("example") DicomtojpegtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dicomtojpegtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomToJpegTask
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dicomtojpegtask record);
}