package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Dicombulkdata;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.DicombulkdataExample;

public interface DicombulkdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    long countByExample(DicombulkdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int deleteByExample(DicombulkdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int insert(Dicombulkdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int insertSelective(Dicombulkdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    List<Dicombulkdata> selectByExample(DicombulkdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    Dicombulkdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dicombulkdata record, @Param("example") DicombulkdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dicombulkdata record, @Param("example") DicombulkdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dicombulkdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.DicomBulkData
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dicombulkdata record);
}