package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Instance;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.InstanceExample;

public interface InstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    long countByExample(InstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int deleteByExample(InstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String x00080018);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int insert(Instance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int insertSelective(Instance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    List<Instance> selectByExample(InstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    Instance selectByPrimaryKey(String x00080018);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Instance record, @Param("example") InstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Instance record, @Param("example") InstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Instance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Instance record);
}