package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Patient;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.PatientExample;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    long countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    List<Patient> selectByExample(PatientExample example);

    
    Cursor<Patient> selectByExampleCursor(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    Patient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Patient
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Patient record);
}