package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Performingphysicianname;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.PerformingphysiciannameExample;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.PerformingphysiciannameKey;

public interface PerformingphysiciannameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    long countByExample(PerformingphysiciannameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int deleteByExample(PerformingphysiciannameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PerformingphysiciannameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int insert(Performingphysicianname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int insertSelective(Performingphysicianname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    List<Performingphysicianname> selectByExample(PerformingphysiciannameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    Performingphysicianname selectByPrimaryKey(PerformingphysiciannameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Performingphysicianname record, @Param("example") PerformingphysiciannameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Performingphysicianname record, @Param("example") PerformingphysiciannameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Performingphysicianname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PerformingPhysicianName
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Performingphysicianname record);
}