package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Personname;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.PersonnameExample;

public interface PersonnameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    long countByExample(PersonnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int deleteByExample(PersonnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int insert(Personname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int insertSelective(Personname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    List<Personname> selectByExample(PersonnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    Personname selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Personname record, @Param("example") PersonnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Personname record, @Param("example") PersonnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Personname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.PersonName
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Personname record);
}