package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Seriesrequestattributes;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.SeriesrequestattributesExample;

public interface SeriesrequestattributesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    long countByExample(SeriesrequestattributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int deleteByExample(SeriesrequestattributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int insert(Seriesrequestattributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int insertSelective(Seriesrequestattributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    List<Seriesrequestattributes> selectByExample(SeriesrequestattributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    Seriesrequestattributes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Seriesrequestattributes record, @Param("example") SeriesrequestattributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Seriesrequestattributes record, @Param("example") SeriesrequestattributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Seriesrequestattributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.SeriesRequestAttributes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Seriesrequestattributes record);
}