package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Study;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.StudyExample;

public interface StudyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    long countByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int deleteByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String x0020000d);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int insert(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int insertSelective(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    List<Study> selectByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    Study selectByPrimaryKey(String x0020000d);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Study
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Study record);
}