package org.dcm4che3.tool.dcmqrscp.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.Verifyingobserversq;
import org.dcm4che3.tool.dcmqrscp.mybatis.entity.VerifyingobserversqExample;

public interface VerifyingobserversqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    long countByExample(VerifyingobserversqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int deleteByExample(VerifyingobserversqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int insert(Verifyingobserversq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int insertSelective(Verifyingobserversq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    List<Verifyingobserversq> selectByExample(VerifyingobserversqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    Verifyingobserversq selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Verifyingobserversq record, @Param("example") VerifyingobserversqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Verifyingobserversq record, @Param("example") VerifyingobserversqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Verifyingobserversq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.VerifyingObserverSQ
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Verifyingobserversq record);
}